#!/bin/bash

# BATCH LINK REPLACEMENT FOR ALL /fr FOLDER FILES
echo "=== BATCH FRENCH LINK REPLACEMENT ==="
echo "Target: ALL .html files in /fr/ folder"

# Check if /fr directory exists
if [ ! -d "fr" ]; then
    echo "Error: /fr directory not found!"
    exit 1
fi

# Count total files to process
TOTAL_FILES=$(find fr/ -name "*.html" | wc -l)
echo "Found $TOTAL_FILES HTML files to process"

# Process each file
PROCESSED=0
SKIPPED=0

for TEST_FILE in fr/*.html; do
    if [ -f "$TEST_FILE" ]; then
        echo ""
        echo "Processing: $TEST_FILE"
        
        # MAIN PAGES
        sed -i 's|href="https://unlimited-leads.online/about-us"|href="https://unlimited-leads.online/fr/about-us"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/account"|href="https://unlimited-leads.online/fr/account"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/alternatives"|href="https://unlimited-leads.online/fr/alternatives"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api-documentation"|href="https://unlimited-leads.online/fr/api-documentation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api"|href="https://unlimited-leads.online/fr/api"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/app"|href="https://unlimited-leads.online/fr/app"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/confirmation"|href="https://unlimited-leads.online/fr/confirmation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/demo"|href="https://unlimited-leads.online/fr/demo"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-verification"|href="https://unlimited-leads.online/fr/email-verification"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/index"|href="https://unlimited-leads.online/fr/index"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/login"|href="https://unlimited-leads.online/fr/login"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pricing"|href="https://unlimited-leads.online/fr/pricing"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sign-up"|href="https://unlimited-leads.online/fr/sign-up"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signup"|href="https://unlimited-leads.online/fr/signup"|g' "$TEST_FILE"

        # FREE TOOLS
        sed -i 's|href="https://unlimited-leads.online/bulk-email-finder"|href="https://unlimited-leads.online/fr/bulk-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spam-words-checker"|href="https://unlimited-leads.online/fr/spam-words-checker"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-email-from-phone-number"|href="https://unlimited-leads.online/fr/find-email-from-phone-number"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bulk-mx-lookup"|href="https://unlimited-leads.online/fr/bulk-mx-lookup"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-extractor"|href="https://unlimited-leads.online/fr/email-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spintax-generator"|href="https://unlimited-leads.online/fr/spintax-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-permutator"|href="https://unlimited-leads.online/fr/email-permutator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/google-map-scraper"|href="https://unlimited-leads.online/fr/google-map-scraper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-email-finder"|href="https://unlimited-leads.online/fr/apollo-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-template-generator"|href="https://unlimited-leads.online/fr/ai-email-template-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-reply-generator-free"|href="https://unlimited-leads.online/fr/ai-email-reply-generator-free"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cold-email-generator"|href="https://unlimited-leads.online/fr/cold-email-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-name-generator"|href="https://unlimited-leads.online/fr/email-name-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-headline-generator"|href="https://unlimited-leads.online/fr/linkedin-headline-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-sales-navigator-scrapper"|href="https://unlimited-leads.online/fr/linkedin-sales-navigator-scrapper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/domain-extractor"|href="https://unlimited-leads.online/fr/domain-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/phone-number-extractor"|href="https://unlimited-leads.online/fr/phone-number-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-website-from-company-name-in-bulk"|href="https://unlimited-leads.online/fr/find-website-from-company-name-in-bulk"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-profile-url-finder"|href="https://unlimited-leads.online/fr/linkedin-profile-url-finder"|g' "$TEST_FILE"

        # ALTERNATIVE COMPARISON PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-alternative"|href="https://unlimited-leads.online/fr/adapt-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-alternative"|href="https://unlimited-leads.online/fr/apollo-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-alternative"|href="https://unlimited-leads.online/fr/cognism-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contact-out-alternative"|href="https://unlimited-leads.online/fr/contact-out-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-alternative"|href="https://unlimited-leads.online/fr/evaboot-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-alternative"|href="https://unlimited-leads.online/fr/findthatlead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-alternative"|href="https://unlimited-leads.online/fr/getprospect-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-alternative"|href="https://unlimited-leads.online/fr/hunter-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-alternative"|href="https://unlimited-leads.online/fr/lead411-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-alternative"|href="https://unlimited-leads.online/fr/leadfuze-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-alternative"|href="https://unlimited-leads.online/fr/leadiq-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-alternative"|href="https://unlimited-leads.online/fr/lusha-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-alternative"|href="https://unlimited-leads.online/fr/rocketreach-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-alternative"|href="https://unlimited-leads.online/fr/scrupp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-alternative"|href="https://unlimited-leads.online/fr/seamless-ai-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-alternative"|href="https://unlimited-leads.online/fr/signal-hire-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-alternative"|href="https://unlimited-leads.online/fr/skrapp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-alternative"|href="https://unlimited-leads.online/fr/snov-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-alternative"|href="https://unlimited-leads.online/fr/uplead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-alternative"|href="https://unlimited-leads.online/fr/wiza-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-alternative"|href="https://unlimited-leads.online/fr/woodpecker-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-alternative"|href="https://unlimited-leads.online/fr/zoominfo-alternative"|g' "$TEST_FILE"

        # COMPETITOR PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-competitors"|href="https://unlimited-leads.online/fr/adapt-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aeroleads-competitors"|href="https://unlimited-leads.online/fr/aeroleads-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-competitors"|href="https://unlimited-leads.online/fr/apollo-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-io-competitors"|href="https://unlimited-leads.online/fr/apollo-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-competitors"|href="https://unlimited-leads.online/fr/cognism-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contactout-competitors"|href="https://unlimited-leads.online/fr/contactout-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-competitors"|href="https://unlimited-leads.online/fr/evaboot-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-competitors"|href="https://unlimited-leads.online/fr/findthatlead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-competitors"|href="https://unlimited-leads.online/fr/getprospect-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-competitors"|href="https://unlimited-leads.online/fr/hunter-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-competitors"|href="https://unlimited-leads.online/fr/lead411-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-competitors"|href="https://unlimited-leads.online/fr/leadfuze-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-competitors"|href="https://unlimited-leads.online/fr/leadiq-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-competitors"|href="https://unlimited-leads.online/fr/linkedin-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-competitors"|href="https://unlimited-leads.online/fr/lusha-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-competitors"|href="https://unlimited-leads.online/fr/rocketreach-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-competitors"|href="https://unlimited-leads.online/fr/scrupp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-competitors"|href="https://unlimited-leads.online/fr/seamless-ai-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-competitors"|href="https://unlimited-leads.online/fr/signal-hire-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-competitors"|href="https://unlimited-leads.online/fr/skrapp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-competitors"|href="https://unlimited-leads.online/fr/snov-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-competitors"|href="https://unlimited-leads.online/fr/uplead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/voilanorbert-competitors"|href="https://unlimited-leads.online/fr/voilanorbert-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-competitors"|href="https://unlimited-leads.online/fr/wiza-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-competitors"|href="https://unlimited-leads.online/fr/woodpecker-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-competitors"|href="https://unlimited-leads.online/fr/zoominfo-competitors"|g' "$TEST_FILE"

        # EXECUTIVE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/cdo-email-list"|href="https://unlimited-leads.online/fr/cdo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ceo-email-list"|href="https://unlimited-leads.online/fr/ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cfo-email-list"|href="https://unlimited-leads.online/fr/cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-data-officer-email-list"|href="https://unlimited-leads.online/fr/chief-data-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-information-security-officer-email-list"|href="https://unlimited-leads.online/fr/chief-information-security-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-medical-officer-email-list"|href="https://unlimited-leads.online/fr/chief-medical-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-revenue-officers-email-list"|href="https://unlimited-leads.online/fr/chief-revenue-officers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-sales-officer-email-list"|href="https://unlimited-leads.online/fr/chief-sales-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chro-email-list"|href="https://unlimited-leads.online/fr/chro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cio-email-list"|href="https://unlimited-leads.online/fr/cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cmo-email-list"|href="https://unlimited-leads.online/fr/cmo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cno-email-list"|href="https://unlimited-leads.online/fr/cno-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/coo-email-list"|href="https://unlimited-leads.online/fr/coo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cso-email-list"|href="https://unlimited-leads.online/fr/cso-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cto-email-list"|href="https://unlimited-leads.online/fr/cto-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cxo-email-list"|href="https://unlimited-leads.online/fr/cxo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-email-list"|href="https://unlimited-leads.online/fr/vp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-business-development-email-list"|href="https://unlimited-leads.online/fr/vp-of-business-development-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-sales-email-list"|href="https://unlimited-leads.online/fr/vp-of-sales-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - MEDICAL SPECIALISTS
        sed -i 's|href="https://unlimited-leads.online/anesthesiologist-email-list"|href="https://unlimited-leads.online/fr/anesthesiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiologist-email-list"|href="https://unlimited-leads.online/fr/cardiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chiropractor-email-list"|href="https://unlimited-leads.online/fr/chiropractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetic-surgeons-email-list"|href="https://unlimited-leads.online/fr/cosmetic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dentist-email-list"|href="https://unlimited-leads.online/fr/dentist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/denturists-email-list"|href="https://unlimited-leads.online/fr/denturists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dermatologist-email-list"|href="https://unlimited-leads.online/fr/dermatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endocrinologist-email-list"|href="https://unlimited-leads.online/fr/endocrinologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endodontists-email-list"|href="https://unlimited-leads.online/fr/endodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialist-email-list"|href="https://unlimited-leads.online/fr/ent-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialists-email-list"|href="https://unlimited-leads.online/fr/ent-specialists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/epidemiologist-email-list"|href="https://unlimited-leads.online/fr/epidemiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-medicine-specialist-email-list"|href="https://unlimited-leads.online/fr/family-medicine-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-practitioners-directors-email-list"|href="https://unlimited-leads.online/fr/family-practitioners-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-therapist-email-list"|href="https://unlimited-leads.online/fr/family-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gastroenterologist-email-list"|href="https://unlimited-leads.online/fr/gastroenterologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioner-email-list"|href="https://unlimited-leads.online/fr/general-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioners-email-list"|href="https://unlimited-leads.online/fr/general-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-surgery-email-list"|href="https://unlimited-leads.online/fr/general-surgery-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/geriatrician-email-list"|href="https://unlimited-leads.online/fr/geriatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gynecologist-email-list"|href="https://unlimited-leads.online/fr/gynecologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hematologist-email-list"|href="https://unlimited-leads.online/fr/hematologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/immunologist-email-list"|href="https://unlimited-leads.online/fr/immunologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interventional-cardiologists-email-list"|href="https://unlimited-leads.online/fr/interventional-cardiologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-director-email-list"|href="https://unlimited-leads.online/fr/medical-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neonatologist-email-list"|href="https://unlimited-leads.online/fr/neonatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nephrologist-email-list"|href="https://unlimited-leads.online/fr/nephrologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurologist-email-list"|href="https://unlimited-leads.online/fr/neurologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurosurgeons-email-list"|href="https://unlimited-leads.online/fr/neurosurgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oncologist-email-list"|href="https://unlimited-leads.online/fr/oncologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ophthalmologist-email-list"|href="https://unlimited-leads.online/fr/ophthalmologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-pathologists-email-list"|href="https://unlimited-leads.online/fr/oral-pathologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-surgeons-email-list"|href="https://unlimited-leads.online/fr/oral-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthodontist-email-list"|href="https://unlimited-leads.online/fr/orthodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/otolaryngologist-email-list"|href="https://unlimited-leads.online/fr/otolaryngologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pathologist-email-list"|href="https://unlimited-leads.online/fr/pathologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatric-dentists-email-list"|href="https://unlimited-leads.online/fr/pediatric-dentists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatrician-email-list"|href="https://unlimited-leads.online/fr/pediatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/periodontist-email-list"|href="https://unlimited-leads.online/fr/periodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacist-email-list"|href="https://unlimited-leads.online/fr/pharmacist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-email-list"|href="https://unlimited-leads.online/fr/physician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-recruiters-email-list"|href="https://unlimited-leads.online/fr/physician-recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plastic-surgeons-email-list"|href="https://unlimited-leads.online/fr/plastic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/prosthodontists-email-list"|href="https://unlimited-leads.online/fr/prosthodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychiatrist-email-list"|href="https://unlimited-leads.online/fr/psychiatrist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychologist-email-list"|href="https://unlimited-leads.online/fr/psychologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pulmonologist-email-list"|href="https://unlimited-leads.online/fr/pulmonologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/radiologist-email-list"|href="https://unlimited-leads.online/fr/radiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rheumatologist-email-list"|href="https://unlimited-leads.online/fr/rheumatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rhinologists-email-list"|href="https://unlimited-leads.online/fr/rhinologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/surgeon-email-list"|href="https://unlimited-leads.online/fr/surgeon-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/urologist-email-list"|href="https://unlimited-leads.online/fr/urologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/veterinarian-email-list"|href="https://unlimited-leads.online/fr/veterinarian-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - NURSES & HEALTHCARE STAFF
        sed -i 's|href="https://unlimited-leads.online/acute-care-nurse-practitioners-email-list"|href="https://unlimited-leads.online/fr/acute-care-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ambulatory-care-nurses-email-list"|href="https://unlimited-leads.online/fr/ambulatory-care-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiovascular-technologist-email-list"|href="https://unlimited-leads.online/fr/cardiovascular-technologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/certified-registered-nurse-anaesthetist-email-list"|href="https://unlimited-leads.online/fr/certified-registered-nurse-anaesthetist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-nurse-practitioners-email-list"|href="https://unlimited-leads.online/fr/family-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/licensed-practical-nurse-email-list"|href="https://unlimited-leads.online/fr/licensed-practical-nurse-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/midwife-nurses-email-list"|href="https://unlimited-leads.online/fr/midwife-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioner-email-list"|href="https://unlimited-leads.online/fr/nurse-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioners-email-list"|href="https://unlimited-leads.online/fr/nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurses-email-list"|href="https://unlimited-leads.online/fr/nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-health-nurses-email-list"|href="https://unlimited-leads.online/fr/occupational-health-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthopedic-nurses-email-list"|href="https://unlimited-leads.online/fr/orthopedic-nurses-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - FACILITIES & ORGANIZATIONS
        sed -i 's|href="https://unlimited-leads.online/ambulatory-surgery-centers-email-list"|href="https://unlimited-leads.online/fr/ambulatory-surgery-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/blood-bank-centers-email-list"|href="https://unlimited-leads.online/fr/blood-bank-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/clinics-email-list"|href="https://unlimited-leads.online/fr/clinics-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-equipment-manufacturers-email-list"|href="https://unlimited-leads.online/fr/dental-equipment-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-email-list"|href="https://unlimited-leads.online/fr/healthcare-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-executives-email-list"|href="https://unlimited-leads.online/fr/healthcare-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-industry-email-list"|href="https://unlimited-leads.online/fr/healthcare-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hipaa-compliance-managers-email-list"|href="https://unlimited-leads.online/fr/hipaa-compliance-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-ceo-email-list"|href="https://unlimited-leads.online/fr/hospital-ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cfo-email-list"|href="https://unlimited-leads.online/fr/hospital-cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cio-email-list"|href="https://unlimited-leads.online/fr/hospital-cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-decision-makers-email-list"|href="https://unlimited-leads.online/fr/hospital-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-email-list"|href="https://unlimited-leads.online/fr/hospital-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-procurement-email-list"|href="https://unlimited-leads.online/fr/hospital-procurement-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitals-email-list"|href="https://unlimited-leads.online/fr/hospitals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/med-spa-email-list"|href="https://unlimited-leads.online/fr/med-spa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-industry-email-list"|href="https://unlimited-leads.online/fr/medical-device-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-manufacturers-email-list"|href="https://unlimited-leads.online/fr/medical-device-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-email-list"|href="https://unlimited-leads.online/fr/medical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nursing-homes-email-list"|href="https://unlimited-leads.online/fr/nursing-homes-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmaceutical-email-list"|href="https://unlimited-leads.online/fr/pharmaceutical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacy-email-list"|href="https://unlimited-leads.online/fr/pharmacy-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapy-email-list"|href="https://unlimited-leads.online/fr/physical-therapy-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - OTHER PROFESSIONALS
        sed -i 's|href="https://unlimited-leads.online/audiologist-email-list"|href="https://unlimited-leads.online/fr/audiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-hygenist-email-list"|href="https://unlimited-leads.online/fr/dental-hygenist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/emt-email-list"|href="https://unlimited-leads.online/fr/emt-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/massage-therapist-email-list"|href="https://unlimited-leads.online/fr/massage-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-counselor-email-list"|href="https://unlimited-leads.online/fr/mental-health-counselor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-professionals-email-list"|href="https://unlimited-leads.online/fr/mental-health-professionals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nutritionist-email-list"|href="https://unlimited-leads.online/fr/nutritionist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-therapist-email-list"|href="https://unlimited-leads.online/fr/occupational-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paramedic-email-list"|href="https://unlimited-leads.online/fr/paramedic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-trainer-email-list"|href="https://unlimited-leads.online/fr/personal-trainer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapist-email-list"|href="https://unlimited-leads.online/fr/physical-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/therapist-email-list"|href="https://unlimited-leads.online/fr/therapist-email-list"|g' "$TEST_FILE"

        # PROFESSIONAL SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/accountants-email-list"|href="https://unlimited-leads.online/fr/accountants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-clerk-email-list"|href="https://unlimited-leads.online/fr/accounting-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-email-list"|href="https://unlimited-leads.online/fr/accounting-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architect-email-list"|href="https://unlimited-leads.online/fr/architect-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/attorney-email-list"|href="https://unlimited-leads.online/fr/attorney-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/auditors-email-list"|href="https://unlimited-leads.online/fr/auditors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bankruptcy-lawyers-email-list"|href="https://unlimited-leads.online/fr/bankruptcy-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/copywriter-email-list"|href="https://unlimited-leads.online/fr/copywriter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cpa-email-list"|href="https://unlimited-leads.online/fr/cpa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/criminal-lawyers-email-list"|href="https://unlimited-leads.online/fr/criminal-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-consultant-email-list"|href="https://unlimited-leads.online/fr/environmental-consultant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/financial-clerk-email-list"|href="https://unlimited-leads.online/fr/financial-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/law-firms-email-list"|href="https://unlimited-leads.online/fr/law-firms-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-injury-lawyers-email-list"|href="https://unlimited-leads.online/fr/personal-injury-lawyers-email-list"|g' "$TEST_FILE"

        # HR & MANAGEMENT EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/brand-manager-email-list"|href="https://unlimited-leads.online/fr/brand-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/executive-assistants-email-list"|href="https://unlimited-leads.online/fr/executive-assistants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-management-email-list"|href="https://unlimited-leads.online/fr/facility-management-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-managers-email-list"|href="https://unlimited-leads.online/fr/facility-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-directors-email-list"|href="https://unlimited-leads.online/fr/hr-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-email-list"|href="https://unlimited-leads.online/fr/hr-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-executives-email-list"|href="https://unlimited-leads.online/fr/hr-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/human-resources-email-list"|href="https://unlimited-leads.online/fr/human-resources-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-directors-email-list"|href="https://unlimited-leads.online/fr/marketing-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recruiters-email-list"|href="https://unlimited-leads.online/fr/recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sales-director-email-list"|href="https://unlimited-leads.online/fr/sales-director-email-list"|g' "$TEST_FILE"

        # EDUCATION EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/athletic-director-email-list"|href="https://unlimited-leads.online/fr/athletic-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/librarian-email-list"|href="https://unlimited-leads.online/fr/librarian-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/principal-email-list"|href="https://unlimited-leads.online/fr/principal-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/superintendent-email-list"|href="https://unlimited-leads.online/fr/superintendent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/teacher-email-list"|href="https://unlimited-leads.online/fr/teacher-email-list"|g' "$TEST_FILE"

        # TECHNOLOGY & ENGINEERING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/engineer-email-list"|href="https://unlimited-leads.online/fr/engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/engineering-email-list"|href="https://unlimited-leads.online/fr/engineering-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-engineers"|href="https://unlimited-leads.online/fr/email-list-of-engineers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-engineer-email-list"|href="https://unlimited-leads.online/fr/environmental-engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/it-decision-makers-email-list"|href="https://unlimited-leads.online/fr/it-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/msp-email-list"|href="https://unlimited-leads.online/fr/msp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/software-engineers-email-list"|href="https://unlimited-leads.online/fr/software-engineers-email-list"|g' "$TEST_FILE"

        # INDUSTRY EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/ada-email-list"|href="https://unlimited-leads.online/fr/ada-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-agencies-email-list"|href="https://unlimited-leads.online/fr/advertising-agencies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-professional-email-list"|href="https://unlimited-leads.online/fr/advertising-professional-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agricultural-equipment-dealer-email-list"|href="https://unlimited-leads.online/fr/agricultural-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agriculture-industry-email-list"|href="https://unlimited-leads.online/fr/agriculture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/airlines-industry-email-list"|href="https://unlimited-leads.online/fr/airlines-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/animation-industry-email-list"|href="https://unlimited-leads.online/fr/animation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apparel-and-fashion-industry-email-list"|href="https://unlimited-leads.online/fr/apparel-and-fashion-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architectural-industry-email-list"|href="https://unlimited-leads.online/fr/architectural-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architecture-and-planning-industry-email-list"|href="https://unlimited-leads.online/fr/architecture-and-planning-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/arts-and-crafts-industry-email-list"|href="https://unlimited-leads.online/fr/arts-and-crafts-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-email-list"|href="https://unlimited-leads.online/fr/automotive-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-email-list"|href="https://unlimited-leads.online/fr/aviation-and-aerospace-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-industry-email-list"|href="https://unlimited-leads.online/fr/aviation-and-aerospace-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-industry-email-list"|href="https://unlimited-leads.online/fr/aviation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/banking-email-list"|href="https://unlimited-leads.online/fr/banking-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/beauty-industry-email-list"|href="https://unlimited-leads.online/fr/beauty-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-email-list"|href="https://unlimited-leads.online/fr/biotechnology-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-industry-email-list"|href="https://unlimited-leads.online/fr/biotechnology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/broadcast-media-industry-email-list"|href="https://unlimited-leads.online/fr/broadcast-media-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/building-materials-industry-email-list"|href="https://unlimited-leads.online/fr/building-materials-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-supplies-and-equipment-industry-email-list"|href="https://unlimited-leads.online/fr/business-supplies-and-equipment-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/call-center-industry-email-list"|href="https://unlimited-leads.online/fr/call-center-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/capital-markets-industry-email-list"|href="https://unlimited-leads.online/fr/capital-markets-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chemicals-industry-email-list"|href="https://unlimited-leads.online/fr/chemicals-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civic-and-social-organization-industry-email-list"|href="https://unlimited-leads.online/fr/civic-and-social-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civil-engineering-industry-email-list"|href="https://unlimited-leads.online/fr/civil-engineering-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-and-network-security-industry-email-list"|href="https://unlimited-leads.online/fr/computer-and-network-security-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-networking-industry-email-list"|href="https://unlimited-leads.online/fr/computer-networking-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-software-industry-email-list"|href="https://unlimited-leads.online/fr/computer-software-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-industry-email-list"|href="https://unlimited-leads.online/fr/construction-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-electronics-industry-email-list"|href="https://unlimited-leads.online/fr/consumer-electronics-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-goods-industry-email-list"|href="https://unlimited-leads.online/fr/consumer-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-services-industry-email-list"|href="https://unlimited-leads.online/fr/consumer-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/defense-and-space-industry-email-list"|href="https://unlimited-leads.online/fr/defense-and-space-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/design-industry-email-list"|href="https://unlimited-leads.online/fr/design-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/education-industry-email-list"|href="https://unlimited-leads.online/fr/education-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrical-and-electronic-manufacturing-industry-email-list"|href="https://unlimited-leads.online/fr/electrical-and-electronic-manufacturing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-services-industry-email-list"|href="https://unlimited-leads.online/fr/environmental-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/events-services-industry-email-list"|href="https://unlimited-leads.online/fr/events-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facilities-and-services-industry-email-list"|href="https://unlimited-leads.online/fr/facilities-and-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/finance-industry-email-list"|href="https://unlimited-leads.online/fr/finance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-and-beverage-industry-email-list"|href="https://unlimited-leads.online/fr/food-and-beverage-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/furniture-industry-email-list"|href="https://unlimited-leads.online/fr/furniture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-administration-industry-email-list"|href="https://unlimited-leads.online/fr/government-administration-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/health-wellness-and-fitness-industry-email-list"|href="https://unlimited-leads.online/fr/health-wellness-and-fitness-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitality-industry-email-list"|href="https://unlimited-leads.online/fr/hospitality-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/industry-email-list"|href="https://unlimited-leads.online/fr/industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-industry-email-list"|href="https://unlimited-leads.online/fr/insurance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/internet-industry-email-list"|href="https://unlimited-leads.online/fr/internet-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/legal-services-industry-email-list"|href="https://unlimited-leads.online/fr/legal-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leisure-industry-email-list"|href="https://unlimited-leads.online/fr/leisure-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-and-supply-chain-industry-email-list"|href="https://unlimited-leads.online/fr/logistics-and-supply-chain-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/luxury-goods-and-jewelry-industry-email-list"|href="https://unlimited-leads.online/fr/luxury-goods-and-jewelry-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/machinery-industry-email-list"|href="https://unlimited-leads.online/fr/machinery-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/management-consulting-industry-email-list"|href="https://unlimited-leads.online/fr/management-consulting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-email-list"|href="https://unlimited-leads.online/fr/manufacturing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/maritime-industry-email-list"|href="https://unlimited-leads.online/fr/maritime-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-and-advertising-industry-email-list"|href="https://unlimited-leads.online/fr/marketing-and-advertising-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/media-production-industry-email-list"|href="https://unlimited-leads.online/fr/media-production-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mining-industry-email-list"|href="https://unlimited-leads.online/fr/mining-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oil-and-gas-industry-email-list"|href="https://unlimited-leads.online/fr/oil-and-gas-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/packaging-industry-email-list"|href="https://unlimited-leads.online/fr/packaging-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paper-and-forest-products-industry-email-list"|href="https://unlimited-leads.online/fr/paper-and-forest-products-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/political-organization-industry-email-list"|href="https://unlimited-leads.online/fr/political-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/printing-and-publishing-email-list"|href="https://unlimited-leads.online/fr/printing-and-publishing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/public-safety-industry-email-list"|href="https://unlimited-leads.online/fr/public-safety-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/railroad-transportation-email-list"|href="https://unlimited-leads.online/fr/railroad-transportation-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-email-list"|href="https://unlimited-leads.online/fr/retail-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sporting-goods-industry-email-list"|href="https://unlimited-leads.online/fr/sporting-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/staffing-and-recruiting-industry-email-list"|href="https://unlimited-leads.online/fr/staffing-and-recruiting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/technology-industry-email-list"|href="https://unlimited-leads.online/fr/technology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/telecom-industry-email-list"|href="https://unlimited-leads.online/fr/telecom-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/transportation-industry-email-list"|href="https://unlimited-leads.online/fr/transportation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-industry-email-list"|href="https://unlimited-leads.online/fr/travel-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/utilities-industry-email-list"|href="https://unlimited-leads.online/fr/utilities-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/venture-capital-and-private-equity-industry-email-list"|href="https://unlimited-leads.online/fr/venture-capital-and-private-equity-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehousing-industry-email-list"|href="https://unlimited-leads.online/fr/warehousing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wholesale-industry-email-list"|href="https://unlimited-leads.online/fr/wholesale-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wine-and-spirits-industry-email-list"|href="https://unlimited-leads.online/fr/wine-and-spirits-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/writing-and-editing-industry-email-list"|href="https://unlimited-leads.online/fr/writing-and-editing-industry-email-list"|g' "$TEST_FILE"

        # BUSINESS & RETAIL EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/auto-dealer-email-list"|href="https://unlimited-leads.online/fr/auto-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-mechanic-email-list"|href="https://unlimited-leads.online/fr/automotive-mechanic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bank-email-list"|href="https://unlimited-leads.online/fr/bank-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/barber-email-list"|href="https://unlimited-leads.online/fr/barber-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-owner-email-list"|href="https://unlimited-leads.online/fr/business-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/caterer-email-list"|href="https://unlimited-leads.online/fr/caterer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cleaning-service-email-list"|href="https://unlimited-leads.online/fr/cleaning-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-companies-email-list"|href="https://unlimited-leads.online/fr/construction-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-email-list"|href="https://unlimited-leads.online/fr/construction-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractor-email-list"|href="https://unlimited-leads.online/fr/contractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractors-email-list"|href="https://unlimited-leads.online/fr/contractors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/convenience-store-owner-email-list"|href="https://unlimited-leads.online/fr/convenience-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/courier-service-email-list"|href="https://unlimited-leads.online/fr/courier-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/delivery-service-email-list"|href="https://unlimited-leads.online/fr/delivery-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dry-cleaner-email-list"|href="https://unlimited-leads.online/fr/dry-cleaner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-small-business-owners"|href="https://unlimited-leads.online/fr/email-list-of-small-business-owners"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-beverage-email-list"|href="https://unlimited-leads.online/fr/food-beverage-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-processing-company-email-list"|href="https://unlimited-leads.online/fr/food-processing-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-truck-owner-email-list"|href="https://unlimited-leads.online/fr/food-truck-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/freight-broker-email-list"|href="https://unlimited-leads.online/fr/freight-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-director-email-list"|href="https://unlimited-leads.online/fr/funeral-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-home-email-list"|href="https://unlimited-leads.online/fr/funeral-home-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gas-station-owner-email-list"|href="https://unlimited-leads.online/fr/gas-station-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gift-shop-email-list"|href="https://unlimited-leads.online/fr/gift-shop-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/grocery-store-manager-email-list"|href="https://unlimited-leads.online/fr/grocery-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hotel-email-list"|href="https://unlimited-leads.online/fr/hotel-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agent-email-list"|href="https://unlimited-leads.online/fr/insurance-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agents-email-list"|href="https://unlimited-leads.online/fr/insurance-agents-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/janitorial-service-email-list"|href="https://unlimited-leads.online/fr/janitorial-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/jewelry-store-email-list"|href="https://unlimited-leads.online/fr/jewelry-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/laundromat-owner-email-list"|href="https://unlimited-leads.online/fr/laundromat-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/loan-officer-email-list"|href="https://unlimited-leads.online/fr/loan-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/locksmith-email-list"|href="https://unlimited-leads.online/fr/locksmith-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-coordinator-email-list"|href="https://unlimited-leads.online/fr/logistics-coordinator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-manager-email-list"|href="https://unlimited-leads.online/fr/manufacturing-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-agency-email-list"|href="https://unlimited-leads.online/fr/marketing-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-broker-email-list"|href="https://unlimited-leads.online/fr/mortgage-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-brokers-email-list"|href="https://unlimited-leads.online/fr/mortgage-brokers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/moving-company-email-list"|href="https://unlimited-leads.online/fr/moving-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/organic-food-producer-email-list"|href="https://unlimited-leads.online/fr/organic-food-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-company-email-list"|href="https://unlimited-leads.online/fr/pest-control-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-email-list"|href="https://unlimited-leads.online/fr/pest-control-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pet-store-owner-email-list"|href="https://unlimited-leads.online/fr/pet-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-management-companies-email-list"|href="https://unlimited-leads.online/fr/property-management-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-manager-email-list"|href="https://unlimited-leads.online/fr/property-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recycling-company-email-list"|href="https://unlimited-leads.online/fr/recycling-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/renewable-energy-company-email-list"|href="https://unlimited-leads.online/fr/renewable-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-email-list"|href="https://unlimited-leads.online/fr/restaurant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-industry-email-list"|href="https://unlimited-leads.online/fr/restaurant-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-email-list"|href="https://unlimited-leads.online/fr/retail-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-manager-email-list"|href="https://unlimited-leads.online/fr/retail-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/security-company-email-list"|href="https://unlimited-leads.online/fr/security-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/shipping-company-email-list"|href="https://unlimited-leads.online/fr/shipping-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/small-business-owners-email-list"|href="https://unlimited-leads.online/fr/small-business-owners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-energy-company-email-list"|href="https://unlimited-leads.online/fr/solar-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/supply-chain-email-list"|href="https://unlimited-leads.online/fr/supply-chain-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agency-email-list"|href="https://unlimited-leads.online/fr/travel-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agent-email-list"|href="https://unlimited-leads.online/fr/travel-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-and-tourism-email-list"|href="https://unlimited-leads.online/fr/travel-and-tourism-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/trucking-company-email-list"|href="https://unlimited-leads.online/fr/trucking-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehouse-manager-email-list"|href="https://unlimited-leads.online/fr/warehouse-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/waste-management-company-email-list"|href="https://unlimited-leads.online/fr/waste-management-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wind-energy-company-email-list"|href="https://unlimited-leads.online/fr/wind-energy-company-email-list"|g' "$TEST_FILE"

        # SKILLED TRADES & SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/appliance-repair-technician-email-list"|href="https://unlimited-leads.online/fr/appliance-repair-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/carpet-installer-email-list"|href="https://unlimited-leads.online/fr/carpet-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologist-email-list"|href="https://unlimited-leads.online/fr/cosmetologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologists-email-list"|href="https://unlimited-leads.online/fr/cosmetologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrician-email-list"|href="https://unlimited-leads.online/fr/electrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/esthetician-email-list"|href="https://unlimited-leads.online/fr/esthetician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/flooring-installer-email-list"|href="https://unlimited-leads.online/fr/flooring-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hair-stylist-email-list"|href="https://unlimited-leads.online/fr/hair-stylist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hvac-technician-email-list"|href="https://unlimited-leads.online/fr/hvac-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/landscaper-email-list"|href="https://unlimited-leads.online/fr/landscaper-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nail-technician-email-list"|href="https://unlimited-leads.online/fr/nail-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/painter-email-list"|href="https://unlimited-leads.online/fr/painter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plumbers-email-list"|href="https://unlimited-leads.online/fr/plumbers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/private-security-guard-email-list"|href="https://unlimited-leads.online/fr/private-security-guard-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/roofer-email-list"|href="https://unlimited-leads.online/fr/roofer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-panel-installer-email-list"|href="https://unlimited-leads.online/fr/solar-panel-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tree-service-email-list"|href="https://unlimited-leads.online/fr/tree-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/welder-email-list"|href="https://unlimited-leads.online/fr/welder-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/window-installer-email-list"|href="https://unlimited-leads.online/fr/window-installer-email-list"|g' "$TEST_FILE"

        # CREATIVE & MEDIA EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/art-director-email-list"|href="https://unlimited-leads.online/fr/art-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/content-creator-email-list"|href="https://unlimited-leads.online/fr/content-creator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-interior-designers"|href="https://unlimited-leads.online/fr/email-list-of-interior-designers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-organizers-email-list"|href="https://unlimited-leads.online/fr/event-organizers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-planner-email-list"|href="https://unlimited-leads.online/fr/event-planner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/film-producer-email-list"|href="https://unlimited-leads.online/fr/film-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/graphic-designer-email-list"|href="https://unlimited-leads.online/fr/graphic-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interior-designer-email-list"|href="https://unlimited-leads.online/fr/interior-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/photographer-email-list"|href="https://unlimited-leads.online/fr/photographer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-media-manager-email-list"|href="https://unlimited-leads.online/fr/social-media-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/video-producer-email-list"|href="https://unlimited-leads.online/fr/video-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/web-designer-email-list"|href="https://unlimited-leads.online/fr/web-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wedding-planner-email-list"|href="https://unlimited-leads.online/fr/wedding-planner-email-list"|g' "$TEST_FILE"

        # FITNESS & SPORTS EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/fitness-instructor-email-list"|href="https://unlimited-leads.online/fr/fitness-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-course-email-list"|href="https://unlimited-leads.online/fr/golf-course-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-pro-email-list"|href="https://unlimited-leads.online/fr/golf-pro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gym-owner-email-list"|href="https://unlimited-leads.online/fr/gym-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pilates-instructor-email-list"|href="https://unlimited-leads.online/fr/pilates-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recreation-center-email-list"|href="https://unlimited-leads.online/fr/recreation-center-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spa-owner-email-list"|href="https://unlimited-leads.online/fr/spa-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-coach-email-list"|href="https://unlimited-leads.online/fr/sports-coach-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-equipment-dealer-email-list"|href="https://unlimited-leads.online/fr/sports-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/swimming-instructor-email-list"|href="https://unlimited-leads.online/fr/swimming-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tennis-instructor-email-list"|href="https://unlimited-leads.online/fr/tennis-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/yoga-instructor-email-list"|href="https://unlimited-leads.online/fr/yoga-instructor-email-list"|g' "$TEST_FILE"

        # AGRICULTURE & FARMING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/crop-farmer-email-list"|href="https://unlimited-leads.online/fr/crop-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dairy-farmer-email-list"|href="https://unlimited-leads.online/fr/dairy-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/farmer-email-list"|href="https://unlimited-leads.online/fr/farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/livestock-farmer-email-list"|href="https://unlimited-leads.online/fr/livestock-farmer-email-list"|g' "$TEST_FILE"

        # GOVERNMENT & PUBLIC SERVICE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/city-council-email-list"|href="https://unlimited-leads.online/fr/city-council-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/community-organizer-email-list"|href="https://unlimited-leads.online/fr/community-organizer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/county-official-email-list"|href="https://unlimited-leads.online/fr/county-official-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/firefighter-email-list"|href="https://unlimited-leads.online/fr/firefighter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-employee-email-list"|href="https://unlimited-leads.online/fr/government-employee-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mayor-email-list"|href="https://unlimited-leads.online/fr/mayor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/municipal-worker-email-list"|href="https://unlimited-leads.online/fr/municipal-worker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/police-department-email-list"|href="https://unlimited-leads.online/fr/police-department-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-worker-email-list"|href="https://unlimited-leads.online/fr/social-worker-email-list"|g' "$TEST_FILE"

        ((PROCESSED++))
    else
        echo "Skipping: $TEST_FILE (not a file)"
        ((SKIPPED++))
    fi
done

echo ""
echo "=== PROCESSING COMPLETE ==="
echo "Processed: $PROCESSED files"
echo "Skipped: $SKIPPED files"
