#!/bin/bash

# BATCH LINK REPLACEMENT FOR ALL /es FOLDER FILES
echo "=== BATCH FRENCH LINK REPLACEMENT ==="
echo "Target: ALL .html files in /es/ folder"

# Check if /es directory exists
if [ ! -d "fr" ]; then
    echo "Error: /es directory not found!"
    exit 1
fi

# Count total files to process
TOTAL_FILES=$(find fr/ -name "*.html" | wc -l)
echo "Found $TOTAL_FILES HTML files to process"

# Process each file
PROCESSED=0
SKIPPED=0

for TEST_FILE in fr/*.html; do
    if [ -f "$TEST_FILE" ]; then
        echo ""
        echo "Processing: $TEST_FILE"
        
        # MAIN PAGES
        sed -i 's|href="https://unlimited-leads.online/about-us"|href="https://unlimited-leads.online/es/about-us"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/account"|href="https://unlimited-leads.online/es/account"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/alternatives"|href="https://unlimited-leads.online/es/alternatives"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api-documentation"|href="https://unlimited-leads.online/es/api-documentation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api"|href="https://unlimited-leads.online/es/api"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/app"|href="https://unlimited-leads.online/es/app"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/confirmation"|href="https://unlimited-leads.online/es/confirmation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/demo"|href="https://unlimited-leads.online/es/demo"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-verification"|href="https://unlimited-leads.online/es/email-verification"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/index"|href="https://unlimited-leads.online/es/index"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/login"|href="https://unlimited-leads.online/es/login"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pricing"|href="https://unlimited-leads.online/es/pricing"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sign-up"|href="https://unlimited-leads.online/es/sign-up"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signup"|href="https://unlimited-leads.online/es/signup"|g' "$TEST_FILE"

        # FREE TOOLS
        sed -i 's|href="https://unlimited-leads.online/bulk-email-finder"|href="https://unlimited-leads.online/es/bulk-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spam-words-checker"|href="https://unlimited-leads.online/es/spam-words-checker"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-email-from-phone-number"|href="https://unlimited-leads.online/es/find-email-from-phone-number"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bulk-mx-lookup"|href="https://unlimited-leads.online/es/bulk-mx-lookup"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-extractor"|href="https://unlimited-leads.online/es/email-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spintax-generator"|href="https://unlimited-leads.online/es/spintax-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-permutator"|href="https://unlimited-leads.online/es/email-permutator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/google-map-scraper"|href="https://unlimited-leads.online/es/google-map-scraper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-email-finder"|href="https://unlimited-leads.online/es/apollo-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-template-generator"|href="https://unlimited-leads.online/es/ai-email-template-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-reply-generator-free"|href="https://unlimited-leads.online/es/ai-email-reply-generator-free"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cold-email-generator"|href="https://unlimited-leads.online/es/cold-email-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-name-generator"|href="https://unlimited-leads.online/es/email-name-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-headline-generator"|href="https://unlimited-leads.online/es/linkedin-headline-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-sales-navigator-scrapper"|href="https://unlimited-leads.online/es/linkedin-sales-navigator-scrapper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/domain-extractor"|href="https://unlimited-leads.online/es/domain-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/phone-number-extractor"|href="https://unlimited-leads.online/es/phone-number-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-website-from-company-name-in-bulk"|href="https://unlimited-leads.online/es/find-website-from-company-name-in-bulk"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-profile-url-finder"|href="https://unlimited-leads.online/es/linkedin-profile-url-finder"|g' "$TEST_FILE"

        # ALTERNATIVE COMPARISON PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-alternative"|href="https://unlimited-leads.online/es/adapt-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-alternative"|href="https://unlimited-leads.online/es/apollo-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-alternative"|href="https://unlimited-leads.online/es/cognism-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contact-out-alternative"|href="https://unlimited-leads.online/es/contact-out-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-alternative"|href="https://unlimited-leads.online/es/evaboot-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-alternative"|href="https://unlimited-leads.online/es/findthatlead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-alternative"|href="https://unlimited-leads.online/es/getprospect-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-alternative"|href="https://unlimited-leads.online/es/hunter-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-alternative"|href="https://unlimited-leads.online/es/lead411-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-alternative"|href="https://unlimited-leads.online/es/leadfuze-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-alternative"|href="https://unlimited-leads.online/es/leadiq-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-alternative"|href="https://unlimited-leads.online/es/lusha-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-alternative"|href="https://unlimited-leads.online/es/rocketreach-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-alternative"|href="https://unlimited-leads.online/es/scrupp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-alternative"|href="https://unlimited-leads.online/es/seamless-ai-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-alternative"|href="https://unlimited-leads.online/es/signal-hire-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-alternative"|href="https://unlimited-leads.online/es/skrapp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-alternative"|href="https://unlimited-leads.online/es/snov-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-alternative"|href="https://unlimited-leads.online/es/uplead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-alternative"|href="https://unlimited-leads.online/es/wiza-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-alternative"|href="https://unlimited-leads.online/es/woodpecker-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-alternative"|href="https://unlimited-leads.online/es/zoominfo-alternative"|g' "$TEST_FILE"

        # COMPETITOR PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-competitors"|href="https://unlimited-leads.online/es/adapt-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aeroleads-competitors"|href="https://unlimited-leads.online/es/aeroleads-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-competitors"|href="https://unlimited-leads.online/es/apollo-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-io-competitors"|href="https://unlimited-leads.online/es/apollo-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-competitors"|href="https://unlimited-leads.online/es/cognism-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contactout-competitors"|href="https://unlimited-leads.online/es/contactout-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-competitors"|href="https://unlimited-leads.online/es/evaboot-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-competitors"|href="https://unlimited-leads.online/es/findthatlead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-competitors"|href="https://unlimited-leads.online/es/getprospect-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-competitors"|href="https://unlimited-leads.online/es/hunter-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-competitors"|href="https://unlimited-leads.online/es/lead411-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-competitors"|href="https://unlimited-leads.online/es/leadfuze-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-competitors"|href="https://unlimited-leads.online/es/leadiq-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-competitors"|href="https://unlimited-leads.online/es/linkedin-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-competitors"|href="https://unlimited-leads.online/es/lusha-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-competitors"|href="https://unlimited-leads.online/es/rocketreach-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-competitors"|href="https://unlimited-leads.online/es/scrupp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-competitors"|href="https://unlimited-leads.online/es/seamless-ai-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-competitors"|href="https://unlimited-leads.online/es/signal-hire-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-competitors"|href="https://unlimited-leads.online/es/skrapp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-competitors"|href="https://unlimited-leads.online/es/snov-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-competitors"|href="https://unlimited-leads.online/es/uplead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/voilanorbert-competitors"|href="https://unlimited-leads.online/es/voilanorbert-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-competitors"|href="https://unlimited-leads.online/es/wiza-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-competitors"|href="https://unlimited-leads.online/es/woodpecker-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-competitors"|href="https://unlimited-leads.online/es/zoominfo-competitors"|g' "$TEST_FILE"

        # EXECUTIVE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/cdo-email-list"|href="https://unlimited-leads.online/es/cdo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ceo-email-list"|href="https://unlimited-leads.online/es/ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cfo-email-list"|href="https://unlimited-leads.online/es/cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-data-officer-email-list"|href="https://unlimited-leads.online/es/chief-data-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-information-security-officer-email-list"|href="https://unlimited-leads.online/es/chief-information-security-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-medical-officer-email-list"|href="https://unlimited-leads.online/es/chief-medical-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-revenue-officers-email-list"|href="https://unlimited-leads.online/es/chief-revenue-officers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-sales-officer-email-list"|href="https://unlimited-leads.online/es/chief-sales-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chro-email-list"|href="https://unlimited-leads.online/es/chro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cio-email-list"|href="https://unlimited-leads.online/es/cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cmo-email-list"|href="https://unlimited-leads.online/es/cmo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cno-email-list"|href="https://unlimited-leads.online/es/cno-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/coo-email-list"|href="https://unlimited-leads.online/es/coo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cso-email-list"|href="https://unlimited-leads.online/es/cso-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cto-email-list"|href="https://unlimited-leads.online/es/cto-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cxo-email-list"|href="https://unlimited-leads.online/es/cxo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-email-list"|href="https://unlimited-leads.online/es/vp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-business-development-email-list"|href="https://unlimited-leads.online/es/vp-of-business-development-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-sales-email-list"|href="https://unlimited-leads.online/es/vp-of-sales-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - MEDICAL SPECIALISTS
        sed -i 's|href="https://unlimited-leads.online/anesthesiologist-email-list"|href="https://unlimited-leads.online/es/anesthesiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiologist-email-list"|href="https://unlimited-leads.online/es/cardiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chiropractor-email-list"|href="https://unlimited-leads.online/es/chiropractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetic-surgeons-email-list"|href="https://unlimited-leads.online/es/cosmetic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dentist-email-list"|href="https://unlimited-leads.online/es/dentist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/denturists-email-list"|href="https://unlimited-leads.online/es/denturists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dermatologist-email-list"|href="https://unlimited-leads.online/es/dermatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endocrinologist-email-list"|href="https://unlimited-leads.online/es/endocrinologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endodontists-email-list"|href="https://unlimited-leads.online/es/endodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialist-email-list"|href="https://unlimited-leads.online/es/ent-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialists-email-list"|href="https://unlimited-leads.online/es/ent-specialists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/epidemiologist-email-list"|href="https://unlimited-leads.online/es/epidemiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-medicine-specialist-email-list"|href="https://unlimited-leads.online/es/family-medicine-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-practitioners-directors-email-list"|href="https://unlimited-leads.online/es/family-practitioners-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-therapist-email-list"|href="https://unlimited-leads.online/es/family-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gastroenterologist-email-list"|href="https://unlimited-leads.online/es/gastroenterologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioner-email-list"|href="https://unlimited-leads.online/es/general-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioners-email-list"|href="https://unlimited-leads.online/es/general-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-surgery-email-list"|href="https://unlimited-leads.online/es/general-surgery-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/geriatrician-email-list"|href="https://unlimited-leads.online/es/geriatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gynecologist-email-list"|href="https://unlimited-leads.online/es/gynecologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hematologist-email-list"|href="https://unlimited-leads.online/es/hematologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/immunologist-email-list"|href="https://unlimited-leads.online/es/immunologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interventional-cardiologists-email-list"|href="https://unlimited-leads.online/es/interventional-cardiologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-director-email-list"|href="https://unlimited-leads.online/es/medical-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neonatologist-email-list"|href="https://unlimited-leads.online/es/neonatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nephrologist-email-list"|href="https://unlimited-leads.online/es/nephrologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurologist-email-list"|href="https://unlimited-leads.online/es/neurologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurosurgeons-email-list"|href="https://unlimited-leads.online/es/neurosurgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oncologist-email-list"|href="https://unlimited-leads.online/es/oncologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ophthalmologist-email-list"|href="https://unlimited-leads.online/es/ophthalmologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-pathologists-email-list"|href="https://unlimited-leads.online/es/oral-pathologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-surgeons-email-list"|href="https://unlimited-leads.online/es/oral-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthodontist-email-list"|href="https://unlimited-leads.online/es/orthodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/otolaryngologist-email-list"|href="https://unlimited-leads.online/es/otolaryngologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pathologist-email-list"|href="https://unlimited-leads.online/es/pathologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatric-dentists-email-list"|href="https://unlimited-leads.online/es/pediatric-dentists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatrician-email-list"|href="https://unlimited-leads.online/es/pediatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/periodontist-email-list"|href="https://unlimited-leads.online/es/periodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacist-email-list"|href="https://unlimited-leads.online/es/pharmacist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-email-list"|href="https://unlimited-leads.online/es/physician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-recruiters-email-list"|href="https://unlimited-leads.online/es/physician-recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plastic-surgeons-email-list"|href="https://unlimited-leads.online/es/plastic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/prosthodontists-email-list"|href="https://unlimited-leads.online/es/prosthodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychiatrist-email-list"|href="https://unlimited-leads.online/es/psychiatrist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychologist-email-list"|href="https://unlimited-leads.online/es/psychologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pulmonologist-email-list"|href="https://unlimited-leads.online/es/pulmonologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/radiologist-email-list"|href="https://unlimited-leads.online/es/radiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rheumatologist-email-list"|href="https://unlimited-leads.online/es/rheumatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rhinologists-email-list"|href="https://unlimited-leads.online/es/rhinologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/surgeon-email-list"|href="https://unlimited-leads.online/es/surgeon-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/urologist-email-list"|href="https://unlimited-leads.online/es/urologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/veterinarian-email-list"|href="https://unlimited-leads.online/es/veterinarian-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - NURSES & HEALTHCARE STAFF
        sed -i 's|href="https://unlimited-leads.online/acute-care-nurse-practitioners-email-list"|href="https://unlimited-leads.online/es/acute-care-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ambulatory-care-nurses-email-list"|href="https://unlimited-leads.online/es/ambulatory-care-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiovascular-technologist-email-list"|href="https://unlimited-leads.online/es/cardiovascular-technologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/certified-registered-nurse-anaesthetist-email-list"|href="https://unlimited-leads.online/es/certified-registered-nurse-anaesthetist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-nurse-practitioners-email-list"|href="https://unlimited-leads.online/es/family-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/licensed-practical-nurse-email-list"|href="https://unlimited-leads.online/es/licensed-practical-nurse-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/midwife-nurses-email-list"|href="https://unlimited-leads.online/es/midwife-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioner-email-list"|href="https://unlimited-leads.online/es/nurse-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioners-email-list"|href="https://unlimited-leads.online/es/nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurses-email-list"|href="https://unlimited-leads.online/es/nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-health-nurses-email-list"|href="https://unlimited-leads.online/es/occupational-health-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthopedic-nurses-email-list"|href="https://unlimited-leads.online/es/orthopedic-nurses-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - FACILITIES & ORGANIZATIONS
        sed -i 's|href="https://unlimited-leads.online/ambulatory-surgery-centers-email-list"|href="https://unlimited-leads.online/es/ambulatory-surgery-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/blood-bank-centers-email-list"|href="https://unlimited-leads.online/es/blood-bank-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/clinics-email-list"|href="https://unlimited-leads.online/es/clinics-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-equipment-manufacturers-email-list"|href="https://unlimited-leads.online/es/dental-equipment-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-email-list"|href="https://unlimited-leads.online/es/healthcare-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-executives-email-list"|href="https://unlimited-leads.online/es/healthcare-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-industry-email-list"|href="https://unlimited-leads.online/es/healthcare-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hipaa-compliance-managers-email-list"|href="https://unlimited-leads.online/es/hipaa-compliance-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-ceo-email-list"|href="https://unlimited-leads.online/es/hospital-ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cfo-email-list"|href="https://unlimited-leads.online/es/hospital-cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cio-email-list"|href="https://unlimited-leads.online/es/hospital-cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-decision-makers-email-list"|href="https://unlimited-leads.online/es/hospital-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-email-list"|href="https://unlimited-leads.online/es/hospital-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-procurement-email-list"|href="https://unlimited-leads.online/es/hospital-procurement-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitals-email-list"|href="https://unlimited-leads.online/es/hospitals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/med-spa-email-list"|href="https://unlimited-leads.online/es/med-spa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-industry-email-list"|href="https://unlimited-leads.online/es/medical-device-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-manufacturers-email-list"|href="https://unlimited-leads.online/es/medical-device-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-email-list"|href="https://unlimited-leads.online/es/medical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nursing-homes-email-list"|href="https://unlimited-leads.online/es/nursing-homes-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmaceutical-email-list"|href="https://unlimited-leads.online/es/pharmaceutical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacy-email-list"|href="https://unlimited-leads.online/es/pharmacy-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapy-email-list"|href="https://unlimited-leads.online/es/physical-therapy-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - OTHER PROFESSIONALS
        sed -i 's|href="https://unlimited-leads.online/audiologist-email-list"|href="https://unlimited-leads.online/es/audiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-hygenist-email-list"|href="https://unlimited-leads.online/es/dental-hygenist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/emt-email-list"|href="https://unlimited-leads.online/es/emt-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/massage-therapist-email-list"|href="https://unlimited-leads.online/es/massage-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-counselor-email-list"|href="https://unlimited-leads.online/es/mental-health-counselor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-professionals-email-list"|href="https://unlimited-leads.online/es/mental-health-professionals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nutritionist-email-list"|href="https://unlimited-leads.online/es/nutritionist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-therapist-email-list"|href="https://unlimited-leads.online/es/occupational-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paramedic-email-list"|href="https://unlimited-leads.online/es/paramedic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-trainer-email-list"|href="https://unlimited-leads.online/es/personal-trainer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapist-email-list"|href="https://unlimited-leads.online/es/physical-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/therapist-email-list"|href="https://unlimited-leads.online/es/therapist-email-list"|g' "$TEST_FILE"

        # PROFESSIONAL SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/accountants-email-list"|href="https://unlimited-leads.online/es/accountants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-clerk-email-list"|href="https://unlimited-leads.online/es/accounting-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-email-list"|href="https://unlimited-leads.online/es/accounting-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architect-email-list"|href="https://unlimited-leads.online/es/architect-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/attorney-email-list"|href="https://unlimited-leads.online/es/attorney-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/auditors-email-list"|href="https://unlimited-leads.online/es/auditors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bankruptcy-lawyers-email-list"|href="https://unlimited-leads.online/es/bankruptcy-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/copywriter-email-list"|href="https://unlimited-leads.online/es/copywriter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cpa-email-list"|href="https://unlimited-leads.online/es/cpa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/criminal-lawyers-email-list"|href="https://unlimited-leads.online/es/criminal-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-consultant-email-list"|href="https://unlimited-leads.online/es/environmental-consultant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/financial-clerk-email-list"|href="https://unlimited-leads.online/es/financial-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/law-firms-email-list"|href="https://unlimited-leads.online/es/law-firms-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-injury-lawyers-email-list"|href="https://unlimited-leads.online/es/personal-injury-lawyers-email-list"|g' "$TEST_FILE"

        # HR & MANAGEMENT EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/brand-manager-email-list"|href="https://unlimited-leads.online/es/brand-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/executive-assistants-email-list"|href="https://unlimited-leads.online/es/executive-assistants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-management-email-list"|href="https://unlimited-leads.online/es/facility-management-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-managers-email-list"|href="https://unlimited-leads.online/es/facility-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-directors-email-list"|href="https://unlimited-leads.online/es/hr-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-email-list"|href="https://unlimited-leads.online/es/hr-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-executives-email-list"|href="https://unlimited-leads.online/es/hr-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/human-resources-email-list"|href="https://unlimited-leads.online/es/human-resources-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-directors-email-list"|href="https://unlimited-leads.online/es/marketing-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recruiters-email-list"|href="https://unlimited-leads.online/es/recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sales-director-email-list"|href="https://unlimited-leads.online/es/sales-director-email-list"|g' "$TEST_FILE"

        # EDUCATION EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/athletic-director-email-list"|href="https://unlimited-leads.online/es/athletic-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/librarian-email-list"|href="https://unlimited-leads.online/es/librarian-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/principal-email-list"|href="https://unlimited-leads.online/es/principal-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/superintendent-email-list"|href="https://unlimited-leads.online/es/superintendent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/teacher-email-list"|href="https://unlimited-leads.online/es/teacher-email-list"|g' "$TEST_FILE"

        # TECHNOLOGY & ENGINEERING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/engineer-email-list"|href="https://unlimited-leads.online/es/engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/engineering-email-list"|href="https://unlimited-leads.online/es/engineering-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-engineers"|href="https://unlimited-leads.online/es/email-list-of-engineers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-engineer-email-list"|href="https://unlimited-leads.online/es/environmental-engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/it-decision-makers-email-list"|href="https://unlimited-leads.online/es/it-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/msp-email-list"|href="https://unlimited-leads.online/es/msp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/software-engineers-email-list"|href="https://unlimited-leads.online/es/software-engineers-email-list"|g' "$TEST_FILE"

        # INDUSTRY EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/ada-email-list"|href="https://unlimited-leads.online/es/ada-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-agencies-email-list"|href="https://unlimited-leads.online/es/advertising-agencies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-professional-email-list"|href="https://unlimited-leads.online/es/advertising-professional-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agricultural-equipment-dealer-email-list"|href="https://unlimited-leads.online/es/agricultural-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agriculture-industry-email-list"|href="https://unlimited-leads.online/es/agriculture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/airlines-industry-email-list"|href="https://unlimited-leads.online/es/airlines-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/animation-industry-email-list"|href="https://unlimited-leads.online/es/animation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apparel-and-fashion-industry-email-list"|href="https://unlimited-leads.online/es/apparel-and-fashion-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architectural-industry-email-list"|href="https://unlimited-leads.online/es/architectural-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architecture-and-planning-industry-email-list"|href="https://unlimited-leads.online/es/architecture-and-planning-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/arts-and-crafts-industry-email-list"|href="https://unlimited-leads.online/es/arts-and-crafts-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-email-list"|href="https://unlimited-leads.online/es/automotive-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-email-list"|href="https://unlimited-leads.online/es/aviation-and-aerospace-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-industry-email-list"|href="https://unlimited-leads.online/es/aviation-and-aerospace-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-industry-email-list"|href="https://unlimited-leads.online/es/aviation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/banking-email-list"|href="https://unlimited-leads.online/es/banking-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/beauty-industry-email-list"|href="https://unlimited-leads.online/es/beauty-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-email-list"|href="https://unlimited-leads.online/es/biotechnology-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-industry-email-list"|href="https://unlimited-leads.online/es/biotechnology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/broadcast-media-industry-email-list"|href="https://unlimited-leads.online/es/broadcast-media-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/building-materials-industry-email-list"|href="https://unlimited-leads.online/es/building-materials-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-supplies-and-equipment-industry-email-list"|href="https://unlimited-leads.online/es/business-supplies-and-equipment-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/call-center-industry-email-list"|href="https://unlimited-leads.online/es/call-center-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/capital-markets-industry-email-list"|href="https://unlimited-leads.online/es/capital-markets-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chemicals-industry-email-list"|href="https://unlimited-leads.online/es/chemicals-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civic-and-social-organization-industry-email-list"|href="https://unlimited-leads.online/es/civic-and-social-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civil-engineering-industry-email-list"|href="https://unlimited-leads.online/es/civil-engineering-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-and-network-security-industry-email-list"|href="https://unlimited-leads.online/es/computer-and-network-security-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-networking-industry-email-list"|href="https://unlimited-leads.online/es/computer-networking-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-software-industry-email-list"|href="https://unlimited-leads.online/es/computer-software-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-industry-email-list"|href="https://unlimited-leads.online/es/construction-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-electronics-industry-email-list"|href="https://unlimited-leads.online/es/consumer-electronics-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-goods-industry-email-list"|href="https://unlimited-leads.online/es/consumer-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-services-industry-email-list"|href="https://unlimited-leads.online/es/consumer-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/defense-and-space-industry-email-list"|href="https://unlimited-leads.online/es/defense-and-space-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/design-industry-email-list"|href="https://unlimited-leads.online/es/design-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/education-industry-email-list"|href="https://unlimited-leads.online/es/education-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrical-and-electronic-manufacturing-industry-email-list"|href="https://unlimited-leads.online/es/electrical-and-electronic-manufacturing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-services-industry-email-list"|href="https://unlimited-leads.online/es/environmental-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/events-services-industry-email-list"|href="https://unlimited-leads.online/es/events-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facilities-and-services-industry-email-list"|href="https://unlimited-leads.online/es/facilities-and-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/finance-industry-email-list"|href="https://unlimited-leads.online/es/finance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-and-beverage-industry-email-list"|href="https://unlimited-leads.online/es/food-and-beverage-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/furniture-industry-email-list"|href="https://unlimited-leads.online/es/furniture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-administration-industry-email-list"|href="https://unlimited-leads.online/es/government-administration-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/health-wellness-and-fitness-industry-email-list"|href="https://unlimited-leads.online/es/health-wellness-and-fitness-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitality-industry-email-list"|href="https://unlimited-leads.online/es/hospitality-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/industry-email-list"|href="https://unlimited-leads.online/es/industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-industry-email-list"|href="https://unlimited-leads.online/es/insurance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/internet-industry-email-list"|href="https://unlimited-leads.online/es/internet-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/legal-services-industry-email-list"|href="https://unlimited-leads.online/es/legal-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leisure-industry-email-list"|href="https://unlimited-leads.online/es/leisure-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-and-supply-chain-industry-email-list"|href="https://unlimited-leads.online/es/logistics-and-supply-chain-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/luxury-goods-and-jewelry-industry-email-list"|href="https://unlimited-leads.online/es/luxury-goods-and-jewelry-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/machinery-industry-email-list"|href="https://unlimited-leads.online/es/machinery-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/management-consulting-industry-email-list"|href="https://unlimited-leads.online/es/management-consulting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-email-list"|href="https://unlimited-leads.online/es/manufacturing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/maritime-industry-email-list"|href="https://unlimited-leads.online/es/maritime-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-and-advertising-industry-email-list"|href="https://unlimited-leads.online/es/marketing-and-advertising-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/media-production-industry-email-list"|href="https://unlimited-leads.online/es/media-production-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mining-industry-email-list"|href="https://unlimited-leads.online/es/mining-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oil-and-gas-industry-email-list"|href="https://unlimited-leads.online/es/oil-and-gas-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/packaging-industry-email-list"|href="https://unlimited-leads.online/es/packaging-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paper-and-forest-products-industry-email-list"|href="https://unlimited-leads.online/es/paper-and-forest-products-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/political-organization-industry-email-list"|href="https://unlimited-leads.online/es/political-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/printing-and-publishing-email-list"|href="https://unlimited-leads.online/es/printing-and-publishing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/public-safety-industry-email-list"|href="https://unlimited-leads.online/es/public-safety-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/railroad-transportation-email-list"|href="https://unlimited-leads.online/es/railroad-transportation-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-email-list"|href="https://unlimited-leads.online/es/retail-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sporting-goods-industry-email-list"|href="https://unlimited-leads.online/es/sporting-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/staffing-and-recruiting-industry-email-list"|href="https://unlimited-leads.online/es/staffing-and-recruiting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/technology-industry-email-list"|href="https://unlimited-leads.online/es/technology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/telecom-industry-email-list"|href="https://unlimited-leads.online/es/telecom-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/transportation-industry-email-list"|href="https://unlimited-leads.online/es/transportation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-industry-email-list"|href="https://unlimited-leads.online/es/travel-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/utilities-industry-email-list"|href="https://unlimited-leads.online/es/utilities-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/venture-capital-and-private-equity-industry-email-list"|href="https://unlimited-leads.online/es/venture-capital-and-private-equity-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehousing-industry-email-list"|href="https://unlimited-leads.online/es/warehousing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wholesale-industry-email-list"|href="https://unlimited-leads.online/es/wholesale-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wine-and-spirits-industry-email-list"|href="https://unlimited-leads.online/es/wine-and-spirits-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/writing-and-editing-industry-email-list"|href="https://unlimited-leads.online/es/writing-and-editing-industry-email-list"|g' "$TEST_FILE"

        # BUSINESS & RETAIL EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/auto-dealer-email-list"|href="https://unlimited-leads.online/es/auto-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-mechanic-email-list"|href="https://unlimited-leads.online/es/automotive-mechanic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bank-email-list"|href="https://unlimited-leads.online/es/bank-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/barber-email-list"|href="https://unlimited-leads.online/es/barber-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-owner-email-list"|href="https://unlimited-leads.online/es/business-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/caterer-email-list"|href="https://unlimited-leads.online/es/caterer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cleaning-service-email-list"|href="https://unlimited-leads.online/es/cleaning-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-companies-email-list"|href="https://unlimited-leads.online/es/construction-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-email-list"|href="https://unlimited-leads.online/es/construction-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractor-email-list"|href="https://unlimited-leads.online/es/contractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractors-email-list"|href="https://unlimited-leads.online/es/contractors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/convenience-store-owner-email-list"|href="https://unlimited-leads.online/es/convenience-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/courier-service-email-list"|href="https://unlimited-leads.online/es/courier-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/delivery-service-email-list"|href="https://unlimited-leads.online/es/delivery-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dry-cleaner-email-list"|href="https://unlimited-leads.online/es/dry-cleaner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-small-business-owners"|href="https://unlimited-leads.online/es/email-list-of-small-business-owners"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-beverage-email-list"|href="https://unlimited-leads.online/es/food-beverage-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-processing-company-email-list"|href="https://unlimited-leads.online/es/food-processing-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-truck-owner-email-list"|href="https://unlimited-leads.online/es/food-truck-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/eseight-broker-email-list"|href="https://unlimited-leads.online/es/eseight-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-director-email-list"|href="https://unlimited-leads.online/es/funeral-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-home-email-list"|href="https://unlimited-leads.online/es/funeral-home-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gas-station-owner-email-list"|href="https://unlimited-leads.online/es/gas-station-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gift-shop-email-list"|href="https://unlimited-leads.online/es/gift-shop-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/grocery-store-manager-email-list"|href="https://unlimited-leads.online/es/grocery-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hotel-email-list"|href="https://unlimited-leads.online/es/hotel-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agent-email-list"|href="https://unlimited-leads.online/es/insurance-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agents-email-list"|href="https://unlimited-leads.online/es/insurance-agents-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/janitorial-service-email-list"|href="https://unlimited-leads.online/es/janitorial-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/jewelry-store-email-list"|href="https://unlimited-leads.online/es/jewelry-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/laundromat-owner-email-list"|href="https://unlimited-leads.online/es/laundromat-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/loan-officer-email-list"|href="https://unlimited-leads.online/es/loan-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/locksmith-email-list"|href="https://unlimited-leads.online/es/locksmith-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-coordinator-email-list"|href="https://unlimited-leads.online/es/logistics-coordinator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-manager-email-list"|href="https://unlimited-leads.online/es/manufacturing-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-agency-email-list"|href="https://unlimited-leads.online/es/marketing-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-broker-email-list"|href="https://unlimited-leads.online/es/mortgage-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-brokers-email-list"|href="https://unlimited-leads.online/es/mortgage-brokers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/moving-company-email-list"|href="https://unlimited-leads.online/es/moving-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/organic-food-producer-email-list"|href="https://unlimited-leads.online/es/organic-food-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-company-email-list"|href="https://unlimited-leads.online/es/pest-control-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-email-list"|href="https://unlimited-leads.online/es/pest-control-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pet-store-owner-email-list"|href="https://unlimited-leads.online/es/pet-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-management-companies-email-list"|href="https://unlimited-leads.online/es/property-management-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-manager-email-list"|href="https://unlimited-leads.online/es/property-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recycling-company-email-list"|href="https://unlimited-leads.online/es/recycling-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/renewable-energy-company-email-list"|href="https://unlimited-leads.online/es/renewable-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-email-list"|href="https://unlimited-leads.online/es/restaurant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-industry-email-list"|href="https://unlimited-leads.online/es/restaurant-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-email-list"|href="https://unlimited-leads.online/es/retail-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-manager-email-list"|href="https://unlimited-leads.online/es/retail-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/security-company-email-list"|href="https://unlimited-leads.online/es/security-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/shipping-company-email-list"|href="https://unlimited-leads.online/es/shipping-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/small-business-owners-email-list"|href="https://unlimited-leads.online/es/small-business-owners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-energy-company-email-list"|href="https://unlimited-leads.online/es/solar-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/supply-chain-email-list"|href="https://unlimited-leads.online/es/supply-chain-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agency-email-list"|href="https://unlimited-leads.online/es/travel-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agent-email-list"|href="https://unlimited-leads.online/es/travel-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-and-tourism-email-list"|href="https://unlimited-leads.online/es/travel-and-tourism-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/trucking-company-email-list"|href="https://unlimited-leads.online/es/trucking-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehouse-manager-email-list"|href="https://unlimited-leads.online/es/warehouse-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/waste-management-company-email-list"|href="https://unlimited-leads.online/es/waste-management-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wind-energy-company-email-list"|href="https://unlimited-leads.online/es/wind-energy-company-email-list"|g' "$TEST_FILE"

        # SKILLED TRADES & SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/appliance-repair-technician-email-list"|href="https://unlimited-leads.online/es/appliance-repair-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/carpet-installer-email-list"|href="https://unlimited-leads.online/es/carpet-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologist-email-list"|href="https://unlimited-leads.online/es/cosmetologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologists-email-list"|href="https://unlimited-leads.online/es/cosmetologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrician-email-list"|href="https://unlimited-leads.online/es/electrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/esthetician-email-list"|href="https://unlimited-leads.online/es/esthetician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/flooring-installer-email-list"|href="https://unlimited-leads.online/es/flooring-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hair-stylist-email-list"|href="https://unlimited-leads.online/es/hair-stylist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hvac-technician-email-list"|href="https://unlimited-leads.online/es/hvac-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/landscaper-email-list"|href="https://unlimited-leads.online/es/landscaper-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nail-technician-email-list"|href="https://unlimited-leads.online/es/nail-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/painter-email-list"|href="https://unlimited-leads.online/es/painter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plumbers-email-list"|href="https://unlimited-leads.online/es/plumbers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/private-security-guard-email-list"|href="https://unlimited-leads.online/es/private-security-guard-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/roofer-email-list"|href="https://unlimited-leads.online/es/roofer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-panel-installer-email-list"|href="https://unlimited-leads.online/es/solar-panel-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tree-service-email-list"|href="https://unlimited-leads.online/es/tree-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/welder-email-list"|href="https://unlimited-leads.online/es/welder-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/window-installer-email-list"|href="https://unlimited-leads.online/es/window-installer-email-list"|g' "$TEST_FILE"

        # CREATIVE & MEDIA EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/art-director-email-list"|href="https://unlimited-leads.online/es/art-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/content-creator-email-list"|href="https://unlimited-leads.online/es/content-creator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-interior-designers"|href="https://unlimited-leads.online/es/email-list-of-interior-designers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-organizers-email-list"|href="https://unlimited-leads.online/es/event-organizers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-planner-email-list"|href="https://unlimited-leads.online/es/event-planner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/film-producer-email-list"|href="https://unlimited-leads.online/es/film-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/graphic-designer-email-list"|href="https://unlimited-leads.online/es/graphic-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interior-designer-email-list"|href="https://unlimited-leads.online/es/interior-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/photographer-email-list"|href="https://unlimited-leads.online/es/photographer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-media-manager-email-list"|href="https://unlimited-leads.online/es/social-media-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/video-producer-email-list"|href="https://unlimited-leads.online/es/video-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/web-designer-email-list"|href="https://unlimited-leads.online/es/web-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wedding-planner-email-list"|href="https://unlimited-leads.online/es/wedding-planner-email-list"|g' "$TEST_FILE"

        # FITNESS & SPORTS EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/fitness-instructor-email-list"|href="https://unlimited-leads.online/es/fitness-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-course-email-list"|href="https://unlimited-leads.online/es/golf-course-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-pro-email-list"|href="https://unlimited-leads.online/es/golf-pro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gym-owner-email-list"|href="https://unlimited-leads.online/es/gym-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pilates-instructor-email-list"|href="https://unlimited-leads.online/es/pilates-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recreation-center-email-list"|href="https://unlimited-leads.online/es/recreation-center-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spa-owner-email-list"|href="https://unlimited-leads.online/es/spa-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-coach-email-list"|href="https://unlimited-leads.online/es/sports-coach-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-equipment-dealer-email-list"|href="https://unlimited-leads.online/es/sports-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/swimming-instructor-email-list"|href="https://unlimited-leads.online/es/swimming-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tennis-instructor-email-list"|href="https://unlimited-leads.online/es/tennis-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/yoga-instructor-email-list"|href="https://unlimited-leads.online/es/yoga-instructor-email-list"|g' "$TEST_FILE"

        # AGRICULTURE & FARMING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/crop-farmer-email-list"|href="https://unlimited-leads.online/es/crop-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dairy-farmer-email-list"|href="https://unlimited-leads.online/es/dairy-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/farmer-email-list"|href="https://unlimited-leads.online/es/farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/livestock-farmer-email-list"|href="https://unlimited-leads.online/es/livestock-farmer-email-list"|g' "$TEST_FILE"

        # GOVERNMENT & PUBLIC SERVICE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/city-council-email-list"|href="https://unlimited-leads.online/es/city-council-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/community-organizer-email-list"|href="https://unlimited-leads.online/es/community-organizer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/county-official-email-list"|href="https://unlimited-leads.online/es/county-official-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/firefighter-email-list"|href="https://unlimited-leads.online/es/firefighter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-employee-email-list"|href="https://unlimited-leads.online/es/government-employee-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mayor-email-list"|href="https://unlimited-leads.online/es/mayor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/municipal-worker-email-list"|href="https://unlimited-leads.online/es/municipal-worker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/police-department-email-list"|href="https://unlimited-leads.online/es/police-department-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-worker-email-list"|href="https://unlimited-leads.online/es/social-worker-email-list"|g' "$TEST_FILE"

        ((PROCESSED++))
    else
        echo "Skipping: $TEST_FILE (not a file)"
        ((SKIPPED++))
    fi
done

echo ""
echo "=== PROCESSING COMPLETE ==="
echo "Processed: $PROCESSED files"
echo "Skipped: $SKIPPED files"
