#!/bin/bash

# BATCH LINK REPLACEMENT FOR ALL /it FOLDER FILES
echo "=== BATCH ITALIAN LINK REPLACEMENT ==="
echo "Target: ALL .html files in /it/ folder"

# Check if /it directory exists
if [ ! -d "it" ]; then
    echo "Error: /it directory not found!"
    exit 1
fi

# Count total files to process
TOTAL_FILES=$(find it/ -name "*.html" | wc -l)
echo "Found $TOTAL_FILES HTML files to process"

# Process each file
PROCESSED=0
SKIPPED=0

for TEST_FILE in it/*.html; do
    if [ -f "$TEST_FILE" ]; then
        echo ""
        echo "Processing: $TEST_FILE"
        
        # MAIN PAGES
        sed -i 's|href="https://unlimited-leads.online/about-us"|href="https://unlimited-leads.online/it/about-us"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/account"|href="https://unlimited-leads.online/it/account"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/alternatives"|href="https://unlimited-leads.online/it/alternatives"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api-documentation"|href="https://unlimited-leads.online/it/api-documentation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api"|href="https://unlimited-leads.online/it/api"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/app"|href="https://unlimited-leads.online/it/app"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/confirmation"|href="https://unlimited-leads.online/it/confirmation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/demo"|href="https://unlimited-leads.online/it/demo"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-verification"|href="https://unlimited-leads.online/it/email-verification"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/index"|href="https://unlimited-leads.online/it/index"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/login"|href="https://unlimited-leads.online/it/login"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pricing"|href="https://unlimited-leads.online/it/pricing"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sign-up"|href="https://unlimited-leads.online/it/sign-up"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signup"|href="https://unlimited-leads.online/it/signup"|g' "$TEST_FILE"

        # FREE TOOLS
        sed -i 's|href="https://unlimited-leads.online/bulk-email-finder"|href="https://unlimited-leads.online/it/bulk-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spam-words-checker"|href="https://unlimited-leads.online/it/spam-words-checker"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-email-from-phone-number"|href="https://unlimited-leads.online/it/find-email-from-phone-number"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bulk-mx-lookup"|href="https://unlimited-leads.online/it/bulk-mx-lookup"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-extractor"|href="https://unlimited-leads.online/it/email-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spintax-generator"|href="https://unlimited-leads.online/it/spintax-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-permutator"|href="https://unlimited-leads.online/it/email-permutator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/google-map-scraper"|href="https://unlimited-leads.online/it/google-map-scraper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-email-finder"|href="https://unlimited-leads.online/it/apollo-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-template-generator"|href="https://unlimited-leads.online/it/ai-email-template-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-reply-generator-free"|href="https://unlimited-leads.online/it/ai-email-reply-generator-free"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cold-email-generator"|href="https://unlimited-leads.online/it/cold-email-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-name-generator"|href="https://unlimited-leads.online/it/email-name-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-headline-generator"|href="https://unlimited-leads.online/it/linkedin-headline-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-sales-navigator-scrapper"|href="https://unlimited-leads.online/it/linkedin-sales-navigator-scrapper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/domain-extractor"|href="https://unlimited-leads.online/it/domain-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/phone-number-extractor"|href="https://unlimited-leads.online/it/phone-number-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-website-from-company-name-in-bulk"|href="https://unlimited-leads.online/it/find-website-from-company-name-in-bulk"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-profile-url-finder"|href="https://unlimited-leads.online/it/linkedin-profile-url-finder"|g' "$TEST_FILE"

        # ALTERNATIVE COMPARISON PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-alternative"|href="https://unlimited-leads.online/it/adapt-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-alternative"|href="https://unlimited-leads.online/it/apollo-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-alternative"|href="https://unlimited-leads.online/it/cognism-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contact-out-alternative"|href="https://unlimited-leads.online/it/contact-out-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-alternative"|href="https://unlimited-leads.online/it/evaboot-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-alternative"|href="https://unlimited-leads.online/it/findthatlead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-alternative"|href="https://unlimited-leads.online/it/getprospect-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-alternative"|href="https://unlimited-leads.online/it/hunter-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-alternative"|href="https://unlimited-leads.online/it/lead411-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-alternative"|href="https://unlimited-leads.online/it/leadfuze-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-alternative"|href="https://unlimited-leads.online/it/leadiq-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-alternative"|href="https://unlimited-leads.online/it/lusha-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-alternative"|href="https://unlimited-leads.online/it/rocketreach-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-alternative"|href="https://unlimited-leads.online/it/scrupp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-alternative"|href="https://unlimited-leads.online/it/seamless-ai-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-alternative"|href="https://unlimited-leads.online/it/signal-hire-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-alternative"|href="https://unlimited-leads.online/it/skrapp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-alternative"|href="https://unlimited-leads.online/it/snov-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-alternative"|href="https://unlimited-leads.online/it/uplead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-alternative"|href="https://unlimited-leads.online/it/wiza-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-alternative"|href="https://unlimited-leads.online/it/woodpecker-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-alternative"|href="https://unlimited-leads.online/it/zoominfo-alternative"|g' "$TEST_FILE"

        # COMPETITOR PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-competitors"|href="https://unlimited-leads.online/it/adapt-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aeroleads-competitors"|href="https://unlimited-leads.online/it/aeroleads-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-competitors"|href="https://unlimited-leads.online/it/apollo-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-io-competitors"|href="https://unlimited-leads.online/it/apollo-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-competitors"|href="https://unlimited-leads.online/it/cognism-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contactout-competitors"|href="https://unlimited-leads.online/it/contactout-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-competitors"|href="https://unlimited-leads.online/it/evaboot-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-competitors"|href="https://unlimited-leads.online/it/findthatlead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-competitors"|href="https://unlimited-leads.online/it/getprospect-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-competitors"|href="https://unlimited-leads.online/it/hunter-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-competitors"|href="https://unlimited-leads.online/it/lead411-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-competitors"|href="https://unlimited-leads.online/it/leadfuze-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-competitors"|href="https://unlimited-leads.online/it/leadiq-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-competitors"|href="https://unlimited-leads.online/it/linkedin-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-competitors"|href="https://unlimited-leads.online/it/lusha-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-competitors"|href="https://unlimited-leads.online/it/rocketreach-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-competitors"|href="https://unlimited-leads.online/it/scrupp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-competitors"|href="https://unlimited-leads.online/it/seamless-ai-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-competitors"|href="https://unlimited-leads.online/it/signal-hire-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-competitors"|href="https://unlimited-leads.online/it/skrapp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-competitors"|href="https://unlimited-leads.online/it/snov-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-competitors"|href="https://unlimited-leads.online/it/uplead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/voilanorbert-competitors"|href="https://unlimited-leads.online/it/voilanorbert-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-competitors"|href="https://unlimited-leads.online/it/wiza-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-competitors"|href="https://unlimited-leads.online/it/woodpecker-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-competitors"|href="https://unlimited-leads.online/it/zoominfo-competitors"|g' "$TEST_FILE"

        # EXECUTIVE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/cdo-email-list"|href="https://unlimited-leads.online/it/cdo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ceo-email-list"|href="https://unlimited-leads.online/it/ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cfo-email-list"|href="https://unlimited-leads.online/it/cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-data-officer-email-list"|href="https://unlimited-leads.online/it/chief-data-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-information-security-officer-email-list"|href="https://unlimited-leads.online/it/chief-information-security-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-medical-officer-email-list"|href="https://unlimited-leads.online/it/chief-medical-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-revenue-officers-email-list"|href="https://unlimited-leads.online/it/chief-revenue-officers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-sales-officer-email-list"|href="https://unlimited-leads.online/it/chief-sales-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chro-email-list"|href="https://unlimited-leads.online/it/chro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cio-email-list"|href="https://unlimited-leads.online/it/cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cmo-email-list"|href="https://unlimited-leads.online/it/cmo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cno-email-list"|href="https://unlimited-leads.online/it/cno-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/coo-email-list"|href="https://unlimited-leads.online/it/coo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cso-email-list"|href="https://unlimited-leads.online/it/cso-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cto-email-list"|href="https://unlimited-leads.online/it/cto-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cxo-email-list"|href="https://unlimited-leads.online/it/cxo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-email-list"|href="https://unlimited-leads.online/it/vp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-business-development-email-list"|href="https://unlimited-leads.online/it/vp-of-business-development-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-sales-email-list"|href="https://unlimited-leads.online/it/vp-of-sales-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - MEDICAL SPECIALISTS
        sed -i 's|href="https://unlimited-leads.online/anesthesiologist-email-list"|href="https://unlimited-leads.online/it/anesthesiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiologist-email-list"|href="https://unlimited-leads.online/it/cardiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chiropractor-email-list"|href="https://unlimited-leads.online/it/chiropractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetic-surgeons-email-list"|href="https://unlimited-leads.online/it/cosmetic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dentist-email-list"|href="https://unlimited-leads.online/it/dentist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/denturists-email-list"|href="https://unlimited-leads.online/it/denturists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dermatologist-email-list"|href="https://unlimited-leads.online/it/dermatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endocrinologist-email-list"|href="https://unlimited-leads.online/it/endocrinologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endodontists-email-list"|href="https://unlimited-leads.online/it/endodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialist-email-list"|href="https://unlimited-leads.online/it/ent-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialists-email-list"|href="https://unlimited-leads.online/it/ent-specialists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/epidemiologist-email-list"|href="https://unlimited-leads.online/it/epidemiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-medicine-specialist-email-list"|href="https://unlimited-leads.online/it/family-medicine-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-practitioners-directors-email-list"|href="https://unlimited-leads.online/it/family-practitioners-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-therapist-email-list"|href="https://unlimited-leads.online/it/family-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gastroenterologist-email-list"|href="https://unlimited-leads.online/it/gastroenterologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioner-email-list"|href="https://unlimited-leads.online/it/general-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioners-email-list"|href="https://unlimited-leads.online/it/general-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-surgery-email-list"|href="https://unlimited-leads.online/it/general-surgery-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/geriatrician-email-list"|href="https://unlimited-leads.online/it/geriatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gynecologist-email-list"|href="https://unlimited-leads.online/it/gynecologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hematologist-email-list"|href="https://unlimited-leads.online/it/hematologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/immunologist-email-list"|href="https://unlimited-leads.online/it/immunologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interventional-cardiologists-email-list"|href="https://unlimited-leads.online/it/interventional-cardiologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-director-email-list"|href="https://unlimited-leads.online/it/medical-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neonatologist-email-list"|href="https://unlimited-leads.online/it/neonatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nephrologist-email-list"|href="https://unlimited-leads.online/it/nephrologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurologist-email-list"|href="https://unlimited-leads.online/it/neurologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurosurgeons-email-list"|href="https://unlimited-leads.online/it/neurosurgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oncologist-email-list"|href="https://unlimited-leads.online/it/oncologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ophthalmologist-email-list"|href="https://unlimited-leads.online/it/ophthalmologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-pathologists-email-list"|href="https://unlimited-leads.online/it/oral-pathologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-surgeons-email-list"|href="https://unlimited-leads.online/it/oral-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthodontist-email-list"|href="https://unlimited-leads.online/it/orthodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/otolaryngologist-email-list"|href="https://unlimited-leads.online/it/otolaryngologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pathologist-email-list"|href="https://unlimited-leads.online/it/pathologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatric-dentists-email-list"|href="https://unlimited-leads.online/it/pediatric-dentists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatrician-email-list"|href="https://unlimited-leads.online/it/pediatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/periodontist-email-list"|href="https://unlimited-leads.online/it/periodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacist-email-list"|href="https://unlimited-leads.online/it/pharmacist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-email-list"|href="https://unlimited-leads.online/it/physician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-recruiters-email-list"|href="https://unlimited-leads.online/it/physician-recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plastic-surgeons-email-list"|href="https://unlimited-leads.online/it/plastic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/prosthodontists-email-list"|href="https://unlimited-leads.online/it/prosthodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychiatrist-email-list"|href="https://unlimited-leads.online/it/psychiatrist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychologist-email-list"|href="https://unlimited-leads.online/it/psychologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pulmonologist-email-list"|href="https://unlimited-leads.online/it/pulmonologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/radiologist-email-list"|href="https://unlimited-leads.online/it/radiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rheumatologist-email-list"|href="https://unlimited-leads.online/it/rheumatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rhinologists-email-list"|href="https://unlimited-leads.online/it/rhinologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/surgeon-email-list"|href="https://unlimited-leads.online/it/surgeon-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/urologist-email-list"|href="https://unlimited-leads.online/it/urologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/veterinarian-email-list"|href="https://unlimited-leads.online/it/veterinarian-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - NURSES & HEALTHCARE STAFF
        sed -i 's|href="https://unlimited-leads.online/acute-care-nurse-practitioners-email-list"|href="https://unlimited-leads.online/it/acute-care-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ambulatory-care-nurses-email-list"|href="https://unlimited-leads.online/it/ambulatory-care-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiovascular-technologist-email-list"|href="https://unlimited-leads.online/it/cardiovascular-technologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/certified-registered-nurse-anaesthetist-email-list"|href="https://unlimited-leads.online/it/certified-registered-nurse-anaesthetist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-nurse-practitioners-email-list"|href="https://unlimited-leads.online/it/family-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/licensed-practical-nurse-email-list"|href="https://unlimited-leads.online/it/licensed-practical-nurse-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/midwife-nurses-email-list"|href="https://unlimited-leads.online/it/midwife-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioner-email-list"|href="https://unlimited-leads.online/it/nurse-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioners-email-list"|href="https://unlimited-leads.online/it/nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurses-email-list"|href="https://unlimited-leads.online/it/nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-health-nurses-email-list"|href="https://unlimited-leads.online/it/occupational-health-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthopedic-nurses-email-list"|href="https://unlimited-leads.online/it/orthopedic-nurses-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - FACILITIES & ORGANIZATIONS
        sed -i 's|href="https://unlimited-leads.online/ambulatory-surgery-centers-email-list"|href="https://unlimited-leads.online/it/ambulatory-surgery-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/blood-bank-centers-email-list"|href="https://unlimited-leads.online/it/blood-bank-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/clinics-email-list"|href="https://unlimited-leads.online/it/clinics-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-equipment-manufacturers-email-list"|href="https://unlimited-leads.online/it/dental-equipment-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-email-list"|href="https://unlimited-leads.online/it/healthcare-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-executives-email-list"|href="https://unlimited-leads.online/it/healthcare-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-industry-email-list"|href="https://unlimited-leads.online/it/healthcare-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hipaa-compliance-managers-email-list"|href="https://unlimited-leads.online/it/hipaa-compliance-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-ceo-email-list"|href="https://unlimited-leads.online/it/hospital-ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cfo-email-list"|href="https://unlimited-leads.online/it/hospital-cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cio-email-list"|href="https://unlimited-leads.online/it/hospital-cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-decision-makers-email-list"|href="https://unlimited-leads.online/it/hospital-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-email-list"|href="https://unlimited-leads.online/it/hospital-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-procurement-email-list"|href="https://unlimited-leads.online/it/hospital-procurement-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitals-email-list"|href="https://unlimited-leads.online/it/hospitals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/med-spa-email-list"|href="https://unlimited-leads.online/it/med-spa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-industry-email-list"|href="https://unlimited-leads.online/it/medical-device-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-manufacturers-email-list"|href="https://unlimited-leads.online/it/medical-device-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-email-list"|href="https://unlimited-leads.online/it/medical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nursing-homes-email-list"|href="https://unlimited-leads.online/it/nursing-homes-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmaceutical-email-list"|href="https://unlimited-leads.online/it/pharmaceutical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacy-email-list"|href="https://unlimited-leads.online/it/pharmacy-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapy-email-list"|href="https://unlimited-leads.online/it/physical-therapy-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - OTHER PROFESSIONALS
        sed -i 's|href="https://unlimited-leads.online/audiologist-email-list"|href="https://unlimited-leads.online/it/audiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-hygenist-email-list"|href="https://unlimited-leads.online/it/dental-hygenist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/emt-email-list"|href="https://unlimited-leads.online/it/emt-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/massage-therapist-email-list"|href="https://unlimited-leads.online/it/massage-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-counselor-email-list"|href="https://unlimited-leads.online/it/mental-health-counselor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-professionals-email-list"|href="https://unlimited-leads.online/it/mental-health-professionals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nutritionist-email-list"|href="https://unlimited-leads.online/it/nutritionist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-therapist-email-list"|href="https://unlimited-leads.online/it/occupational-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paramedic-email-list"|href="https://unlimited-leads.online/it/paramedic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-trainer-email-list"|href="https://unlimited-leads.online/it/personal-trainer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapist-email-list"|href="https://unlimited-leads.online/it/physical-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/therapist-email-list"|href="https://unlimited-leads.online/it/therapist-email-list"|g' "$TEST_FILE"

        # PROFESSIONAL SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/accountants-email-list"|href="https://unlimited-leads.online/it/accountants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-clerk-email-list"|href="https://unlimited-leads.online/it/accounting-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-email-list"|href="https://unlimited-leads.online/it/accounting-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architect-email-list"|href="https://unlimited-leads.online/it/architect-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/attorney-email-list"|href="https://unlimited-leads.online/it/attorney-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/auditors-email-list"|href="https://unlimited-leads.online/it/auditors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bankruptcy-lawyers-email-list"|href="https://unlimited-leads.online/it/bankruptcy-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/copywriter-email-list"|href="https://unlimited-leads.online/it/copywriter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cpa-email-list"|href="https://unlimited-leads.online/it/cpa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/criminal-lawyers-email-list"|href="https://unlimited-leads.online/it/criminal-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-consultant-email-list"|href="https://unlimited-leads.online/it/environmental-consultant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/financial-clerk-email-list"|href="https://unlimited-leads.online/it/financial-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/law-firms-email-list"|href="https://unlimited-leads.online/it/law-firms-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-injury-lawyers-email-list"|href="https://unlimited-leads.online/it/personal-injury-lawyers-email-list"|g' "$TEST_FILE"

        # HR & MANAGEMENT EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/brand-manager-email-list"|href="https://unlimited-leads.online/it/brand-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/executive-assistants-email-list"|href="https://unlimited-leads.online/it/executive-assistants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-management-email-list"|href="https://unlimited-leads.online/it/facility-management-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-managers-email-list"|href="https://unlimited-leads.online/it/facility-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-directors-email-list"|href="https://unlimited-leads.online/it/hr-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-email-list"|href="https://unlimited-leads.online/it/hr-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-executives-email-list"|href="https://unlimited-leads.online/it/hr-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/human-resources-email-list"|href="https://unlimited-leads.online/it/human-resources-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-directors-email-list"|href="https://unlimited-leads.online/it/marketing-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recruiters-email-list"|href="https://unlimited-leads.online/it/recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sales-director-email-list"|href="https://unlimited-leads.online/it/sales-director-email-list"|g' "$TEST_FILE"

        # EDUCATION EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/athletic-director-email-list"|href="https://unlimited-leads.online/it/athletic-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/librarian-email-list"|href="https://unlimited-leads.online/it/librarian-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/principal-email-list"|href="https://unlimited-leads.online/it/principal-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/superintendent-email-list"|href="https://unlimited-leads.online/it/superintendent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/teacher-email-list"|href="https://unlimited-leads.online/it/teacher-email-list"|g' "$TEST_FILE"

        # TECHNOLOGY & ENGINEERING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/engineer-email-list"|href="https://unlimited-leads.online/it/engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/engineering-email-list"|href="https://unlimited-leads.online/it/engineering-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-engineers"|href="https://unlimited-leads.online/it/email-list-of-engineers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-engineer-email-list"|href="https://unlimited-leads.online/it/environmental-engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/it-decision-makers-email-list"|href="https://unlimited-leads.online/it/it-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/msp-email-list"|href="https://unlimited-leads.online/it/msp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/software-engineers-email-list"|href="https://unlimited-leads.online/it/software-engineers-email-list"|g' "$TEST_FILE"

        # INDUSTRY EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/ada-email-list"|href="https://unlimited-leads.online/it/ada-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-agencies-email-list"|href="https://unlimited-leads.online/it/advertising-agencies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-professional-email-list"|href="https://unlimited-leads.online/it/advertising-professional-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agricultural-equipment-dealer-email-list"|href="https://unlimited-leads.online/it/agricultural-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agriculture-industry-email-list"|href="https://unlimited-leads.online/it/agriculture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/airlines-industry-email-list"|href="https://unlimited-leads.online/it/airlines-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/animation-industry-email-list"|href="https://unlimited-leads.online/it/animation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apparel-and-fashion-industry-email-list"|href="https://unlimited-leads.online/it/apparel-and-fashion-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architectural-industry-email-list"|href="https://unlimited-leads.online/it/architectural-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architecture-and-planning-industry-email-list"|href="https://unlimited-leads.online/it/architecture-and-planning-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/arts-and-crafts-industry-email-list"|href="https://unlimited-leads.online/it/arts-and-crafts-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-email-list"|href="https://unlimited-leads.online/it/automotive-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-email-list"|href="https://unlimited-leads.online/it/aviation-and-aerospace-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-industry-email-list"|href="https://unlimited-leads.online/it/aviation-and-aerospace-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-industry-email-list"|href="https://unlimited-leads.online/it/aviation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/banking-email-list"|href="https://unlimited-leads.online/it/banking-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/beauty-industry-email-list"|href="https://unlimited-leads.online/it/beauty-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-email-list"|href="https://unlimited-leads.online/it/biotechnology-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-industry-email-list"|href="https://unlimited-leads.online/it/biotechnology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/broadcast-media-industry-email-list"|href="https://unlimited-leads.online/it/broadcast-media-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/building-materials-industry-email-list"|href="https://unlimited-leads.online/it/building-materials-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-supplies-and-equipment-industry-email-list"|href="https://unlimited-leads.online/it/business-supplies-and-equipment-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/call-center-industry-email-list"|href="https://unlimited-leads.online/it/call-center-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/capital-markets-industry-email-list"|href="https://unlimited-leads.online/it/capital-markets-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chemicals-industry-email-list"|href="https://unlimited-leads.online/it/chemicals-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civic-and-social-organization-industry-email-list"|href="https://unlimited-leads.online/it/civic-and-social-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civil-engineering-industry-email-list"|href="https://unlimited-leads.online/it/civil-engineering-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-and-network-security-industry-email-list"|href="https://unlimited-leads.online/it/computer-and-network-security-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-networking-industry-email-list"|href="https://unlimited-leads.online/it/computer-networking-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-software-industry-email-list"|href="https://unlimited-leads.online/it/computer-software-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-industry-email-list"|href="https://unlimited-leads.online/it/construction-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-electronics-industry-email-list"|href="https://unlimited-leads.online/it/consumer-electronics-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-goods-industry-email-list"|href="https://unlimited-leads.online/it/consumer-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-services-industry-email-list"|href="https://unlimited-leads.online/it/consumer-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/defense-and-space-industry-email-list"|href="https://unlimited-leads.online/it/defense-and-space-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/design-industry-email-list"|href="https://unlimited-leads.online/it/design-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/education-industry-email-list"|href="https://unlimited-leads.online/it/education-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrical-and-electronic-manufacturing-industry-email-list"|href="https://unlimited-leads.online/it/electrical-and-electronic-manufacturing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-services-industry-email-list"|href="https://unlimited-leads.online/it/environmental-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/events-services-industry-email-list"|href="https://unlimited-leads.online/it/events-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facilities-and-services-industry-email-list"|href="https://unlimited-leads.online/it/facilities-and-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/finance-industry-email-list"|href="https://unlimited-leads.online/it/finance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-and-beverage-industry-email-list"|href="https://unlimited-leads.online/it/food-and-beverage-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/furniture-industry-email-list"|href="https://unlimited-leads.online/it/furniture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-administration-industry-email-list"|href="https://unlimited-leads.online/it/government-administration-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/health-wellness-and-fitness-industry-email-list"|href="https://unlimited-leads.online/it/health-wellness-and-fitness-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitality-industry-email-list"|href="https://unlimited-leads.online/it/hospitality-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/industry-email-list"|href="https://unlimited-leads.online/it/industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-industry-email-list"|href="https://unlimited-leads.online/it/insurance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/internet-industry-email-list"|href="https://unlimited-leads.online/it/internet-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/legal-services-industry-email-list"|href="https://unlimited-leads.online/it/legal-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leisure-industry-email-list"|href="https://unlimited-leads.online/it/leisure-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-and-supply-chain-industry-email-list"|href="https://unlimited-leads.online/it/logistics-and-supply-chain-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/luxury-goods-and-jewelry-industry-email-list"|href="https://unlimited-leads.online/it/luxury-goods-and-jewelry-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/machinery-industry-email-list"|href="https://unlimited-leads.online/it/machinery-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/management-consulting-industry-email-list"|href="https://unlimited-leads.online/it/management-consulting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-email-list"|href="https://unlimited-leads.online/it/manufacturing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/maritime-industry-email-list"|href="https://unlimited-leads.online/it/maritime-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-and-advertising-industry-email-list"|href="https://unlimited-leads.online/it/marketing-and-advertising-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/media-production-industry-email-list"|href="https://unlimited-leads.online/it/media-production-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mining-industry-email-list"|href="https://unlimited-leads.online/it/mining-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oil-and-gas-industry-email-list"|href="https://unlimited-leads.online/it/oil-and-gas-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/packaging-industry-email-list"|href="https://unlimited-leads.online/it/packaging-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paper-and-forest-products-industry-email-list"|href="https://unlimited-leads.online/it/paper-and-forest-products-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/political-organization-industry-email-list"|href="https://unlimited-leads.online/it/political-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/printing-and-publishing-email-list"|href="https://unlimited-leads.online/it/printing-and-publishing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/public-safety-industry-email-list"|href="https://unlimited-leads.online/it/public-safety-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/railroad-transportation-email-list"|href="https://unlimited-leads.online/it/railroad-transportation-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-email-list"|href="https://unlimited-leads.online/it/retail-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sporting-goods-industry-email-list"|href="https://unlimited-leads.online/it/sporting-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/staffing-and-recruiting-industry-email-list"|href="https://unlimited-leads.online/it/staffing-and-recruiting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/technology-industry-email-list"|href="https://unlimited-leads.online/it/technology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/telecom-industry-email-list"|href="https://unlimited-leads.online/it/telecom-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/transportation-industry-email-list"|href="https://unlimited-leads.online/it/transportation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-industry-email-list"|href="https://unlimited-leads.online/it/travel-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/utilities-industry-email-list"|href="https://unlimited-leads.online/it/utilities-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/venture-capital-and-private-equity-industry-email-list"|href="https://unlimited-leads.online/it/venture-capital-and-private-equity-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehousing-industry-email-list"|href="https://unlimited-leads.online/it/warehousing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wholesale-industry-email-list"|href="https://unlimited-leads.online/it/wholesale-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wine-and-spirits-industry-email-list"|href="https://unlimited-leads.online/it/wine-and-spirits-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/writing-and-editing-industry-email-list"|href="https://unlimited-leads.online/it/writing-and-editing-industry-email-list"|g' "$TEST_FILE"

        # BUSINESS & RETAIL EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/auto-dealer-email-list"|href="https://unlimited-leads.online/it/auto-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-mechanic-email-list"|href="https://unlimited-leads.online/it/automotive-mechanic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bank-email-list"|href="https://unlimited-leads.online/it/bank-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/barber-email-list"|href="https://unlimited-leads.online/it/barber-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-owner-email-list"|href="https://unlimited-leads.online/it/business-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/caterer-email-list"|href="https://unlimited-leads.online/it/caterer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cleaning-service-email-list"|href="https://unlimited-leads.online/it/cleaning-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-companies-email-list"|href="https://unlimited-leads.online/it/construction-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-email-list"|href="https://unlimited-leads.online/it/construction-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractor-email-list"|href="https://unlimited-leads.online/it/contractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractors-email-list"|href="https://unlimited-leads.online/it/contractors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/convenience-store-owner-email-list"|href="https://unlimited-leads.online/it/convenience-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/courier-service-email-list"|href="https://unlimited-leads.online/it/courier-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/delivery-service-email-list"|href="https://unlimited-leads.online/it/delivery-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dry-cleaner-email-list"|href="https://unlimited-leads.online/it/dry-cleaner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-small-business-owners"|href="https://unlimited-leads.online/it/email-list-of-small-business-owners"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-beverage-email-list"|href="https://unlimited-leads.online/it/food-beverage-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-processing-company-email-list"|href="https://unlimited-leads.online/it/food-processing-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-truck-owner-email-list"|href="https://unlimited-leads.online/it/food-truck-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/iteight-broker-email-list"|href="https://unlimited-leads.online/it/iteight-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-director-email-list"|href="https://unlimited-leads.online/it/funeral-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-home-email-list"|href="https://unlimited-leads.online/it/funeral-home-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gas-station-owner-email-list"|href="https://unlimited-leads.online/it/gas-station-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gift-shop-email-list"|href="https://unlimited-leads.online/it/gift-shop-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/grocery-store-manager-email-list"|href="https://unlimited-leads.online/it/grocery-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hotel-email-list"|href="https://unlimited-leads.online/it/hotel-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agent-email-list"|href="https://unlimited-leads.online/it/insurance-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agents-email-list"|href="https://unlimited-leads.online/it/insurance-agents-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/janitorial-service-email-list"|href="https://unlimited-leads.online/it/janitorial-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/jewelry-store-email-list"|href="https://unlimited-leads.online/it/jewelry-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/laundromat-owner-email-list"|href="https://unlimited-leads.online/it/laundromat-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/loan-officer-email-list"|href="https://unlimited-leads.online/it/loan-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/locksmith-email-list"|href="https://unlimited-leads.online/it/locksmith-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-coordinator-email-list"|href="https://unlimited-leads.online/it/logistics-coordinator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-manager-email-list"|href="https://unlimited-leads.online/it/manufacturing-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-agency-email-list"|href="https://unlimited-leads.online/it/marketing-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-broker-email-list"|href="https://unlimited-leads.online/it/mortgage-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-brokers-email-list"|href="https://unlimited-leads.online/it/mortgage-brokers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/moving-company-email-list"|href="https://unlimited-leads.online/it/moving-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/organic-food-producer-email-list"|href="https://unlimited-leads.online/it/organic-food-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-company-email-list"|href="https://unlimited-leads.online/it/pest-control-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-email-list"|href="https://unlimited-leads.online/it/pest-control-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pet-store-owner-email-list"|href="https://unlimited-leads.online/it/pet-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-management-companies-email-list"|href="https://unlimited-leads.online/it/property-management-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-manager-email-list"|href="https://unlimited-leads.online/it/property-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recycling-company-email-list"|href="https://unlimited-leads.online/it/recycling-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/renewable-energy-company-email-list"|href="https://unlimited-leads.online/it/renewable-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-email-list"|href="https://unlimited-leads.online/it/restaurant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-industry-email-list"|href="https://unlimited-leads.online/it/restaurant-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-email-list"|href="https://unlimited-leads.online/it/retail-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-manager-email-list"|href="https://unlimited-leads.online/it/retail-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/security-company-email-list"|href="https://unlimited-leads.online/it/security-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/shipping-company-email-list"|href="https://unlimited-leads.online/it/shipping-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/small-business-owners-email-list"|href="https://unlimited-leads.online/it/small-business-owners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-energy-company-email-list"|href="https://unlimited-leads.online/it/solar-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/supply-chain-email-list"|href="https://unlimited-leads.online/it/supply-chain-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agency-email-list"|href="https://unlimited-leads.online/it/travel-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agent-email-list"|href="https://unlimited-leads.online/it/travel-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-and-tourism-email-list"|href="https://unlimited-leads.online/it/travel-and-tourism-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/trucking-company-email-list"|href="https://unlimited-leads.online/it/trucking-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehouse-manager-email-list"|href="https://unlimited-leads.online/it/warehouse-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/waste-management-company-email-list"|href="https://unlimited-leads.online/it/waste-management-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wind-energy-company-email-list"|href="https://unlimited-leads.online/it/wind-energy-company-email-list"|g' "$TEST_FILE"

        # SKILLED TRADES & SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/appliance-repair-technician-email-list"|href="https://unlimited-leads.online/it/appliance-repair-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/carpet-installer-email-list"|href="https://unlimited-leads.online/it/carpet-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologist-email-list"|href="https://unlimited-leads.online/it/cosmetologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologists-email-list"|href="https://unlimited-leads.online/it/cosmetologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrician-email-list"|href="https://unlimited-leads.online/it/electrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/esthetician-email-list"|href="https://unlimited-leads.online/it/esthetician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/flooring-installer-email-list"|href="https://unlimited-leads.online/it/flooring-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hair-stylist-email-list"|href="https://unlimited-leads.online/it/hair-stylist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hvac-technician-email-list"|href="https://unlimited-leads.online/it/hvac-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/landscaper-email-list"|href="https://unlimited-leads.online/it/landscaper-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nail-technician-email-list"|href="https://unlimited-leads.online/it/nail-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/painter-email-list"|href="https://unlimited-leads.online/it/painter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plumbers-email-list"|href="https://unlimited-leads.online/it/plumbers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/private-security-guard-email-list"|href="https://unlimited-leads.online/it/private-security-guard-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/roofer-email-list"|href="https://unlimited-leads.online/it/roofer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-panel-installer-email-list"|href="https://unlimited-leads.online/it/solar-panel-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tree-service-email-list"|href="https://unlimited-leads.online/it/tree-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/welder-email-list"|href="https://unlimited-leads.online/it/welder-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/window-installer-email-list"|href="https://unlimited-leads.online/it/window-installer-email-list"|g' "$TEST_FILE"

        # CREATIVE & MEDIA EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/art-director-email-list"|href="https://unlimited-leads.online/it/art-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/content-creator-email-list"|href="https://unlimited-leads.online/it/content-creator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-interior-designers"|href="https://unlimited-leads.online/it/email-list-of-interior-designers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-organizers-email-list"|href="https://unlimited-leads.online/it/event-organizers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-planner-email-list"|href="https://unlimited-leads.online/it/event-planner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/film-producer-email-list"|href="https://unlimited-leads.online/it/film-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/graphic-designer-email-list"|href="https://unlimited-leads.online/it/graphic-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interior-designer-email-list"|href="https://unlimited-leads.online/it/interior-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/photographer-email-list"|href="https://unlimited-leads.online/it/photographer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-media-manager-email-list"|href="https://unlimited-leads.online/it/social-media-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/video-producer-email-list"|href="https://unlimited-leads.online/it/video-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/web-designer-email-list"|href="https://unlimited-leads.online/it/web-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wedding-planner-email-list"|href="https://unlimited-leads.online/it/wedding-planner-email-list"|g' "$TEST_FILE"

        # FITNESS & SPORTS EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/fitness-instructor-email-list"|href="https://unlimited-leads.online/it/fitness-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-course-email-list"|href="https://unlimited-leads.online/it/golf-course-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-pro-email-list"|href="https://unlimited-leads.online/it/golf-pro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gym-owner-email-list"|href="https://unlimited-leads.online/it/gym-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pilates-instructor-email-list"|href="https://unlimited-leads.online/it/pilates-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recreation-center-email-list"|href="https://unlimited-leads.online/it/recreation-center-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spa-owner-email-list"|href="https://unlimited-leads.online/it/spa-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-coach-email-list"|href="https://unlimited-leads.online/it/sports-coach-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-equipment-dealer-email-list"|href="https://unlimited-leads.online/it/sports-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/swimming-instructor-email-list"|href="https://unlimited-leads.online/it/swimming-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tennis-instructor-email-list"|href="https://unlimited-leads.online/it/tennis-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/yoga-instructor-email-list"|href="https://unlimited-leads.online/it/yoga-instructor-email-list"|g' "$TEST_FILE"

        # AGRICULTURE & FARMING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/crop-farmer-email-list"|href="https://unlimited-leads.online/it/crop-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dairy-farmer-email-list"|href="https://unlimited-leads.online/it/dairy-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/farmer-email-list"|href="https://unlimited-leads.online/it/farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/livestock-farmer-email-list"|href="https://unlimited-leads.online/it/livestock-farmer-email-list"|g' "$TEST_FILE"

        # GOVERNMENT & PUBLIC SERVICE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/city-council-email-list"|href="https://unlimited-leads.online/it/city-council-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/community-organizer-email-list"|href="https://unlimited-leads.online/it/community-organizer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/county-official-email-list"|href="https://unlimited-leads.online/it/county-official-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/firefighter-email-list"|href="https://unlimited-leads.online/it/firefighter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-employee-email-list"|href="https://unlimited-leads.online/it/government-employee-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mayor-email-list"|href="https://unlimited-leads.online/it/mayor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/municipal-worker-email-list"|href="https://unlimited-leads.online/it/municipal-worker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/police-department-email-list"|href="https://unlimited-leads.online/it/police-department-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-worker-email-list"|href="https://unlimited-leads.online/it/social-worker-email-list"|g' "$TEST_FILE"

        ((PROCESSED++))
    else
        echo "Skipping: $TEST_FILE (not a file)"
        ((SKIPPED++))
    fi
done

echo ""
echo "=== PROCESSING COMPLETE ==="
echo "Processed: $PROCESSED files"
echo "Skipped: $SKIPPED files"
