#!/bin/bash

# BATCH LINK REPLACEMENT FOR ALL /pt FOLDER FILES
echo "=== BATCH PORTUGUESE LINK REPLACEMENT ==="
echo "Target: ALL .html files in /pt/ folder"

# Check if /pt directory exists
if [ ! -d "pt" ]; then
    echo "Error: /pt directory not found!"
    exit 1
fi

# Count total files to process
TOTAL_FILES=$(find pt/ -name "*.html" | wc -l)
echo "Found $TOTAL_FILES HTML files to process"

# Process each file
PROCESSED=0
SKIPPED=0

for TEST_FILE in pt/*.html; do
    if [ -f "$TEST_FILE" ]; then
        echo ""
        echo "Processing: $TEST_FILE"
        
        # MAIN PAGES
        sed -i 's|href="https://unlimited-leads.online/about-us"|href="https://unlimited-leads.online/pt/about-us"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/account"|href="https://unlimited-leads.online/pt/account"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/alternatives"|href="https://unlimited-leads.online/pt/alternatives"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api-documentation"|href="https://unlimited-leads.online/pt/api-documentation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api"|href="https://unlimited-leads.online/pt/api"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/app"|href="https://unlimited-leads.online/pt/app"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/confirmation"|href="https://unlimited-leads.online/pt/confirmation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/demo"|href="https://unlimited-leads.online/pt/demo"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-verification"|href="https://unlimited-leads.online/pt/email-verification"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/index"|href="https://unlimited-leads.online/pt/index"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/login"|href="https://unlimited-leads.online/pt/login"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pricing"|href="https://unlimited-leads.online/pt/pricing"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sign-up"|href="https://unlimited-leads.online/pt/sign-up"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signup"|href="https://unlimited-leads.online/pt/signup"|g' "$TEST_FILE"

        # FREE TOOLS
        sed -i 's|href="https://unlimited-leads.online/bulk-email-finder"|href="https://unlimited-leads.online/pt/bulk-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spam-words-checker"|href="https://unlimited-leads.online/pt/spam-words-checker"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-email-from-phone-number"|href="https://unlimited-leads.online/pt/find-email-from-phone-number"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bulk-mx-lookup"|href="https://unlimited-leads.online/pt/bulk-mx-lookup"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-extractor"|href="https://unlimited-leads.online/pt/email-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spintax-generator"|href="https://unlimited-leads.online/pt/spintax-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-permutator"|href="https://unlimited-leads.online/pt/email-permutator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/google-map-scraper"|href="https://unlimited-leads.online/pt/google-map-scraper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-email-finder"|href="https://unlimited-leads.online/pt/apollo-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-template-generator"|href="https://unlimited-leads.online/pt/ai-email-template-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-reply-generator-free"|href="https://unlimited-leads.online/pt/ai-email-reply-generator-free"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cold-email-generator"|href="https://unlimited-leads.online/pt/cold-email-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-name-generator"|href="https://unlimited-leads.online/pt/email-name-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-headline-generator"|href="https://unlimited-leads.online/pt/linkedin-headline-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-sales-navigator-scrapper"|href="https://unlimited-leads.online/pt/linkedin-sales-navigator-scrapper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/domain-extractor"|href="https://unlimited-leads.online/pt/domain-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/phone-number-extractor"|href="https://unlimited-leads.online/pt/phone-number-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-website-from-company-name-in-bulk"|href="https://unlimited-leads.online/pt/find-website-from-company-name-in-bulk"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-profile-url-finder"|href="https://unlimited-leads.online/pt/linkedin-profile-url-finder"|g' "$TEST_FILE"

        # ALTERNATIVE COMPARISON PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-alternative"|href="https://unlimited-leads.online/pt/adapt-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-alternative"|href="https://unlimited-leads.online/pt/apollo-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-alternative"|href="https://unlimited-leads.online/pt/cognism-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contact-out-alternative"|href="https://unlimited-leads.online/pt/contact-out-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-alternative"|href="https://unlimited-leads.online/pt/evaboot-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-alternative"|href="https://unlimited-leads.online/pt/findthatlead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-alternative"|href="https://unlimited-leads.online/pt/getprospect-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-alternative"|href="https://unlimited-leads.online/pt/hunter-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-alternative"|href="https://unlimited-leads.online/pt/lead411-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-alternative"|href="https://unlimited-leads.online/pt/leadfuze-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-alternative"|href="https://unlimited-leads.online/pt/leadiq-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-alternative"|href="https://unlimited-leads.online/pt/lusha-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-alternative"|href="https://unlimited-leads.online/pt/rocketreach-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-alternative"|href="https://unlimited-leads.online/pt/scrupp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-alternative"|href="https://unlimited-leads.online/pt/seamless-ai-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-alternative"|href="https://unlimited-leads.online/pt/signal-hire-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-alternative"|href="https://unlimited-leads.online/pt/skrapp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-alternative"|href="https://unlimited-leads.online/pt/snov-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-alternative"|href="https://unlimited-leads.online/pt/uplead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-alternative"|href="https://unlimited-leads.online/pt/wiza-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-alternative"|href="https://unlimited-leads.online/pt/woodpecker-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-alternative"|href="https://unlimited-leads.online/pt/zoominfo-alternative"|g' "$TEST_FILE"

        # COMPETITOR PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-competitors"|href="https://unlimited-leads.online/pt/adapt-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aeroleads-competitors"|href="https://unlimited-leads.online/pt/aeroleads-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-competitors"|href="https://unlimited-leads.online/pt/apollo-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-io-competitors"|href="https://unlimited-leads.online/pt/apollo-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-competitors"|href="https://unlimited-leads.online/pt/cognism-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contactout-competitors"|href="https://unlimited-leads.online/pt/contactout-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-competitors"|href="https://unlimited-leads.online/pt/evaboot-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-competitors"|href="https://unlimited-leads.online/pt/findthatlead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-competitors"|href="https://unlimited-leads.online/pt/getprospect-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-competitors"|href="https://unlimited-leads.online/pt/hunter-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-competitors"|href="https://unlimited-leads.online/pt/lead411-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-competitors"|href="https://unlimited-leads.online/pt/leadfuze-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-competitors"|href="https://unlimited-leads.online/pt/leadiq-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-competitors"|href="https://unlimited-leads.online/pt/linkedin-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-competitors"|href="https://unlimited-leads.online/pt/lusha-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-competitors"|href="https://unlimited-leads.online/pt/rocketreach-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-competitors"|href="https://unlimited-leads.online/pt/scrupp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-competitors"|href="https://unlimited-leads.online/pt/seamless-ai-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-competitors"|href="https://unlimited-leads.online/pt/signal-hire-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-competitors"|href="https://unlimited-leads.online/pt/skrapp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-competitors"|href="https://unlimited-leads.online/pt/snov-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-competitors"|href="https://unlimited-leads.online/pt/uplead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/voilanorbert-competitors"|href="https://unlimited-leads.online/pt/voilanorbert-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-competitors"|href="https://unlimited-leads.online/pt/wiza-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-competitors"|href="https://unlimited-leads.online/pt/woodpecker-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-competitors"|href="https://unlimited-leads.online/pt/zoominfo-competitors"|g' "$TEST_FILE"

        # EXECUTIVE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/cdo-email-list"|href="https://unlimited-leads.online/pt/cdo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ceo-email-list"|href="https://unlimited-leads.online/pt/ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cfo-email-list"|href="https://unlimited-leads.online/pt/cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-data-officer-email-list"|href="https://unlimited-leads.online/pt/chief-data-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-information-security-officer-email-list"|href="https://unlimited-leads.online/pt/chief-information-security-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-medical-officer-email-list"|href="https://unlimited-leads.online/pt/chief-medical-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-revenue-officers-email-list"|href="https://unlimited-leads.online/pt/chief-revenue-officers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-sales-officer-email-list"|href="https://unlimited-leads.online/pt/chief-sales-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chro-email-list"|href="https://unlimited-leads.online/pt/chro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cio-email-list"|href="https://unlimited-leads.online/pt/cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cmo-email-list"|href="https://unlimited-leads.online/pt/cmo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cno-email-list"|href="https://unlimited-leads.online/pt/cno-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/coo-email-list"|href="https://unlimited-leads.online/pt/coo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cso-email-list"|href="https://unlimited-leads.online/pt/cso-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cto-email-list"|href="https://unlimited-leads.online/pt/cto-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cxo-email-list"|href="https://unlimited-leads.online/pt/cxo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-email-list"|href="https://unlimited-leads.online/pt/vp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-business-development-email-list"|href="https://unlimited-leads.online/pt/vp-of-business-development-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-sales-email-list"|href="https://unlimited-leads.online/pt/vp-of-sales-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - MEDICAL SPECIALISTS
        sed -i 's|href="https://unlimited-leads.online/anesthesiologist-email-list"|href="https://unlimited-leads.online/pt/anesthesiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiologist-email-list"|href="https://unlimited-leads.online/pt/cardiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chiropractor-email-list"|href="https://unlimited-leads.online/pt/chiropractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetic-surgeons-email-list"|href="https://unlimited-leads.online/pt/cosmetic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dentist-email-list"|href="https://unlimited-leads.online/pt/dentist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/denturists-email-list"|href="https://unlimited-leads.online/pt/denturists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dermatologist-email-list"|href="https://unlimited-leads.online/pt/dermatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endocrinologist-email-list"|href="https://unlimited-leads.online/pt/endocrinologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endodontists-email-list"|href="https://unlimited-leads.online/pt/endodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialist-email-list"|href="https://unlimited-leads.online/pt/ent-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialists-email-list"|href="https://unlimited-leads.online/pt/ent-specialists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/epidemiologist-email-list"|href="https://unlimited-leads.online/pt/epidemiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-medicine-specialist-email-list"|href="https://unlimited-leads.online/pt/family-medicine-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-practitioners-directors-email-list"|href="https://unlimited-leads.online/pt/family-practitioners-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-therapist-email-list"|href="https://unlimited-leads.online/pt/family-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gastroenterologist-email-list"|href="https://unlimited-leads.online/pt/gastroenterologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioner-email-list"|href="https://unlimited-leads.online/pt/general-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioners-email-list"|href="https://unlimited-leads.online/pt/general-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-surgery-email-list"|href="https://unlimited-leads.online/pt/general-surgery-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/geriatrician-email-list"|href="https://unlimited-leads.online/pt/geriatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gynecologist-email-list"|href="https://unlimited-leads.online/pt/gynecologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hematologist-email-list"|href="https://unlimited-leads.online/pt/hematologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/immunologist-email-list"|href="https://unlimited-leads.online/pt/immunologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interventional-cardiologists-email-list"|href="https://unlimited-leads.online/pt/interventional-cardiologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-director-email-list"|href="https://unlimited-leads.online/pt/medical-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neonatologist-email-list"|href="https://unlimited-leads.online/pt/neonatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nephrologist-email-list"|href="https://unlimited-leads.online/pt/nephrologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurologist-email-list"|href="https://unlimited-leads.online/pt/neurologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurosurgeons-email-list"|href="https://unlimited-leads.online/pt/neurosurgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oncologist-email-list"|href="https://unlimited-leads.online/pt/oncologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ophthalmologist-email-list"|href="https://unlimited-leads.online/pt/ophthalmologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-pathologists-email-list"|href="https://unlimited-leads.online/pt/oral-pathologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-surgeons-email-list"|href="https://unlimited-leads.online/pt/oral-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthodontist-email-list"|href="https://unlimited-leads.online/pt/orthodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/otolaryngologist-email-list"|href="https://unlimited-leads.online/pt/otolaryngologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pathologist-email-list"|href="https://unlimited-leads.online/pt/pathologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatric-dentists-email-list"|href="https://unlimited-leads.online/pt/pediatric-dentists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatrician-email-list"|href="https://unlimited-leads.online/pt/pediatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/periodontist-email-list"|href="https://unlimited-leads.online/pt/periodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacist-email-list"|href="https://unlimited-leads.online/pt/pharmacist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-email-list"|href="https://unlimited-leads.online/pt/physician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-recruiters-email-list"|href="https://unlimited-leads.online/pt/physician-recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plastic-surgeons-email-list"|href="https://unlimited-leads.online/pt/plastic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/prosthodontists-email-list"|href="https://unlimited-leads.online/pt/prosthodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychiatrist-email-list"|href="https://unlimited-leads.online/pt/psychiatrist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychologist-email-list"|href="https://unlimited-leads.online/pt/psychologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pulmonologist-email-list"|href="https://unlimited-leads.online/pt/pulmonologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/radiologist-email-list"|href="https://unlimited-leads.online/pt/radiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rheumatologist-email-list"|href="https://unlimited-leads.online/pt/rheumatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rhinologists-email-list"|href="https://unlimited-leads.online/pt/rhinologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/surgeon-email-list"|href="https://unlimited-leads.online/pt/surgeon-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/urologist-email-list"|href="https://unlimited-leads.online/pt/urologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/veterinarian-email-list"|href="https://unlimited-leads.online/pt/veterinarian-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - NURSES & HEALTHCARE STAFF
        sed -i 's|href="https://unlimited-leads.online/acute-care-nurse-practitioners-email-list"|href="https://unlimited-leads.online/pt/acute-care-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ambulatory-care-nurses-email-list"|href="https://unlimited-leads.online/pt/ambulatory-care-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiovascular-technologist-email-list"|href="https://unlimited-leads.online/pt/cardiovascular-technologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/certified-registered-nurse-anaesthetist-email-list"|href="https://unlimited-leads.online/pt/certified-registered-nurse-anaesthetist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-nurse-practitioners-email-list"|href="https://unlimited-leads.online/pt/family-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/licensed-practical-nurse-email-list"|href="https://unlimited-leads.online/pt/licensed-practical-nurse-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/midwife-nurses-email-list"|href="https://unlimited-leads.online/pt/midwife-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioner-email-list"|href="https://unlimited-leads.online/pt/nurse-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioners-email-list"|href="https://unlimited-leads.online/pt/nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurses-email-list"|href="https://unlimited-leads.online/pt/nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-health-nurses-email-list"|href="https://unlimited-leads.online/pt/occupational-health-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthopedic-nurses-email-list"|href="https://unlimited-leads.online/pt/orthopedic-nurses-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - FACILITIES & ORGANIZATIONS
        sed -i 's|href="https://unlimited-leads.online/ambulatory-surgery-centers-email-list"|href="https://unlimited-leads.online/pt/ambulatory-surgery-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/blood-bank-centers-email-list"|href="https://unlimited-leads.online/pt/blood-bank-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/clinics-email-list"|href="https://unlimited-leads.online/pt/clinics-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-equipment-manufacturers-email-list"|href="https://unlimited-leads.online/pt/dental-equipment-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-email-list"|href="https://unlimited-leads.online/pt/healthcare-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-executives-email-list"|href="https://unlimited-leads.online/pt/healthcare-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-industry-email-list"|href="https://unlimited-leads.online/pt/healthcare-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hipaa-compliance-managers-email-list"|href="https://unlimited-leads.online/pt/hipaa-compliance-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-ceo-email-list"|href="https://unlimited-leads.online/pt/hospital-ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cfo-email-list"|href="https://unlimited-leads.online/pt/hospital-cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cio-email-list"|href="https://unlimited-leads.online/pt/hospital-cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-decision-makers-email-list"|href="https://unlimited-leads.online/pt/hospital-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-email-list"|href="https://unlimited-leads.online/pt/hospital-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-procurement-email-list"|href="https://unlimited-leads.online/pt/hospital-procurement-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitals-email-list"|href="https://unlimited-leads.online/pt/hospitals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/med-spa-email-list"|href="https://unlimited-leads.online/pt/med-spa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-industry-email-list"|href="https://unlimited-leads.online/pt/medical-device-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-manufacturers-email-list"|href="https://unlimited-leads.online/pt/medical-device-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-email-list"|href="https://unlimited-leads.online/pt/medical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nursing-homes-email-list"|href="https://unlimited-leads.online/pt/nursing-homes-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmaceutical-email-list"|href="https://unlimited-leads.online/pt/pharmaceutical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacy-email-list"|href="https://unlimited-leads.online/pt/pharmacy-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapy-email-list"|href="https://unlimited-leads.online/pt/physical-therapy-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - OTHER PROFESSIONALS
        sed -i 's|href="https://unlimited-leads.online/audiologist-email-list"|href="https://unlimited-leads.online/pt/audiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-hygenist-email-list"|href="https://unlimited-leads.online/pt/dental-hygenist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/emt-email-list"|href="https://unlimited-leads.online/pt/emt-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/massage-therapist-email-list"|href="https://unlimited-leads.online/pt/massage-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-counselor-email-list"|href="https://unlimited-leads.online/pt/mental-health-counselor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-professionals-email-list"|href="https://unlimited-leads.online/pt/mental-health-professionals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nutritionist-email-list"|href="https://unlimited-leads.online/pt/nutritionist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-therapist-email-list"|href="https://unlimited-leads.online/pt/occupational-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paramedic-email-list"|href="https://unlimited-leads.online/pt/paramedic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-trainer-email-list"|href="https://unlimited-leads.online/pt/personal-trainer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapist-email-list"|href="https://unlimited-leads.online/pt/physical-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/therapist-email-list"|href="https://unlimited-leads.online/pt/therapist-email-list"|g' "$TEST_FILE"

        # PROFESSIONAL SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/accountants-email-list"|href="https://unlimited-leads.online/pt/accountants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-clerk-email-list"|href="https://unlimited-leads.online/pt/accounting-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-email-list"|href="https://unlimited-leads.online/pt/accounting-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architect-email-list"|href="https://unlimited-leads.online/pt/architect-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/attorney-email-list"|href="https://unlimited-leads.online/pt/attorney-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/auditors-email-list"|href="https://unlimited-leads.online/pt/auditors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bankruptcy-lawyers-email-list"|href="https://unlimited-leads.online/pt/bankruptcy-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/copywriter-email-list"|href="https://unlimited-leads.online/pt/copywriter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cpa-email-list"|href="https://unlimited-leads.online/pt/cpa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/criminal-lawyers-email-list"|href="https://unlimited-leads.online/pt/criminal-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-consultant-email-list"|href="https://unlimited-leads.online/pt/environmental-consultant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/financial-clerk-email-list"|href="https://unlimited-leads.online/pt/financial-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/law-firms-email-list"|href="https://unlimited-leads.online/pt/law-firms-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-injury-lawyers-email-list"|href="https://unlimited-leads.online/pt/personal-injury-lawyers-email-list"|g' "$TEST_FILE"

        # HR & MANAGEMENT EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/brand-manager-email-list"|href="https://unlimited-leads.online/pt/brand-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/executive-assistants-email-list"|href="https://unlimited-leads.online/pt/executive-assistants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-management-email-list"|href="https://unlimited-leads.online/pt/facility-management-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-managers-email-list"|href="https://unlimited-leads.online/pt/facility-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-directors-email-list"|href="https://unlimited-leads.online/pt/hr-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-email-list"|href="https://unlimited-leads.online/pt/hr-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-executives-email-list"|href="https://unlimited-leads.online/pt/hr-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/human-resources-email-list"|href="https://unlimited-leads.online/pt/human-resources-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-directors-email-list"|href="https://unlimited-leads.online/pt/marketing-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recruiters-email-list"|href="https://unlimited-leads.online/pt/recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sales-director-email-list"|href="https://unlimited-leads.online/pt/sales-director-email-list"|g' "$TEST_FILE"

        # EDUCATION EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/athletic-director-email-list"|href="https://unlimited-leads.online/pt/athletic-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/librarian-email-list"|href="https://unlimited-leads.online/pt/librarian-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/principal-email-list"|href="https://unlimited-leads.online/pt/principal-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/superintendent-email-list"|href="https://unlimited-leads.online/pt/superintendent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/teacher-email-list"|href="https://unlimited-leads.online/pt/teacher-email-list"|g' "$TEST_FILE"

        # TECHNOLOGY & ENGINEERING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/engineer-email-list"|href="https://unlimited-leads.online/pt/engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/engineering-email-list"|href="https://unlimited-leads.online/pt/engineering-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-engineers"|href="https://unlimited-leads.online/pt/email-list-of-engineers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-engineer-email-list"|href="https://unlimited-leads.online/pt/environmental-engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/it-decision-makers-email-list"|href="https://unlimited-leads.online/pt/it-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/msp-email-list"|href="https://unlimited-leads.online/pt/msp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/software-engineers-email-list"|href="https://unlimited-leads.online/pt/software-engineers-email-list"|g' "$TEST_FILE"

        # INDUSTRY EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/ada-email-list"|href="https://unlimited-leads.online/pt/ada-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-agencies-email-list"|href="https://unlimited-leads.online/pt/advertising-agencies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-professional-email-list"|href="https://unlimited-leads.online/pt/advertising-professional-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agricultural-equipment-dealer-email-list"|href="https://unlimited-leads.online/pt/agricultural-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agriculture-industry-email-list"|href="https://unlimited-leads.online/pt/agriculture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/airlines-industry-email-list"|href="https://unlimited-leads.online/pt/airlines-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/animation-industry-email-list"|href="https://unlimited-leads.online/pt/animation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apparel-and-fashion-industry-email-list"|href="https://unlimited-leads.online/pt/apparel-and-fashion-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architectural-industry-email-list"|href="https://unlimited-leads.online/pt/architectural-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architecture-and-planning-industry-email-list"|href="https://unlimited-leads.online/pt/architecture-and-planning-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/arts-and-crafts-industry-email-list"|href="https://unlimited-leads.online/pt/arts-and-crafts-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-email-list"|href="https://unlimited-leads.online/pt/automotive-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-email-list"|href="https://unlimited-leads.online/pt/aviation-and-aerospace-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-industry-email-list"|href="https://unlimited-leads.online/pt/aviation-and-aerospace-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-industry-email-list"|href="https://unlimited-leads.online/pt/aviation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/banking-email-list"|href="https://unlimited-leads.online/pt/banking-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/beauty-industry-email-list"|href="https://unlimited-leads.online/pt/beauty-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-email-list"|href="https://unlimited-leads.online/pt/biotechnology-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-industry-email-list"|href="https://unlimited-leads.online/pt/biotechnology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/broadcast-media-industry-email-list"|href="https://unlimited-leads.online/pt/broadcast-media-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/building-materials-industry-email-list"|href="https://unlimited-leads.online/pt/building-materials-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-supplies-and-equipment-industry-email-list"|href="https://unlimited-leads.online/pt/business-supplies-and-equipment-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/call-center-industry-email-list"|href="https://unlimited-leads.online/pt/call-center-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/capital-markets-industry-email-list"|href="https://unlimited-leads.online/pt/capital-markets-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chemicals-industry-email-list"|href="https://unlimited-leads.online/pt/chemicals-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civic-and-social-organization-industry-email-list"|href="https://unlimited-leads.online/pt/civic-and-social-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civil-engineering-industry-email-list"|href="https://unlimited-leads.online/pt/civil-engineering-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-and-network-security-industry-email-list"|href="https://unlimited-leads.online/pt/computer-and-network-security-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-networking-industry-email-list"|href="https://unlimited-leads.online/pt/computer-networking-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-software-industry-email-list"|href="https://unlimited-leads.online/pt/computer-software-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-industry-email-list"|href="https://unlimited-leads.online/pt/construction-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-electronics-industry-email-list"|href="https://unlimited-leads.online/pt/consumer-electronics-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-goods-industry-email-list"|href="https://unlimited-leads.online/pt/consumer-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-services-industry-email-list"|href="https://unlimited-leads.online/pt/consumer-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/defense-and-space-industry-email-list"|href="https://unlimited-leads.online/pt/defense-and-space-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/design-industry-email-list"|href="https://unlimited-leads.online/pt/design-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/education-industry-email-list"|href="https://unlimited-leads.online/pt/education-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrical-and-electronic-manufacturing-industry-email-list"|href="https://unlimited-leads.online/pt/electrical-and-electronic-manufacturing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-services-industry-email-list"|href="https://unlimited-leads.online/pt/environmental-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/events-services-industry-email-list"|href="https://unlimited-leads.online/pt/events-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facilities-and-services-industry-email-list"|href="https://unlimited-leads.online/pt/facilities-and-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/finance-industry-email-list"|href="https://unlimited-leads.online/pt/finance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-and-beverage-industry-email-list"|href="https://unlimited-leads.online/pt/food-and-beverage-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/furniture-industry-email-list"|href="https://unlimited-leads.online/pt/furniture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-administration-industry-email-list"|href="https://unlimited-leads.online/pt/government-administration-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/health-wellness-and-fitness-industry-email-list"|href="https://unlimited-leads.online/pt/health-wellness-and-fitness-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitality-industry-email-list"|href="https://unlimited-leads.online/pt/hospitality-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/industry-email-list"|href="https://unlimited-leads.online/pt/industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-industry-email-list"|href="https://unlimited-leads.online/pt/insurance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/internet-industry-email-list"|href="https://unlimited-leads.online/pt/internet-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/legal-services-industry-email-list"|href="https://unlimited-leads.online/pt/legal-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leisure-industry-email-list"|href="https://unlimited-leads.online/pt/leisure-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-and-supply-chain-industry-email-list"|href="https://unlimited-leads.online/pt/logistics-and-supply-chain-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/luxury-goods-and-jewelry-industry-email-list"|href="https://unlimited-leads.online/pt/luxury-goods-and-jewelry-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/machinery-industry-email-list"|href="https://unlimited-leads.online/pt/machinery-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/management-consulting-industry-email-list"|href="https://unlimited-leads.online/pt/management-consulting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-email-list"|href="https://unlimited-leads.online/pt/manufacturing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/maritime-industry-email-list"|href="https://unlimited-leads.online/pt/maritime-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-and-advertising-industry-email-list"|href="https://unlimited-leads.online/pt/marketing-and-advertising-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/media-production-industry-email-list"|href="https://unlimited-leads.online/pt/media-production-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mining-industry-email-list"|href="https://unlimited-leads.online/pt/mining-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oil-and-gas-industry-email-list"|href="https://unlimited-leads.online/pt/oil-and-gas-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/packaging-industry-email-list"|href="https://unlimited-leads.online/pt/packaging-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paper-and-forest-products-industry-email-list"|href="https://unlimited-leads.online/pt/paper-and-forest-products-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/political-organization-industry-email-list"|href="https://unlimited-leads.online/pt/political-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/printing-and-publishing-email-list"|href="https://unlimited-leads.online/pt/printing-and-publishing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/public-safety-industry-email-list"|href="https://unlimited-leads.online/pt/public-safety-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/railroad-transportation-email-list"|href="https://unlimited-leads.online/pt/railroad-transportation-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-email-list"|href="https://unlimited-leads.online/pt/retail-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sporting-goods-industry-email-list"|href="https://unlimited-leads.online/pt/sporting-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/staffing-and-recruiting-industry-email-list"|href="https://unlimited-leads.online/pt/staffing-and-recruiting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/technology-industry-email-list"|href="https://unlimited-leads.online/pt/technology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/telecom-industry-email-list"|href="https://unlimited-leads.online/pt/telecom-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/transportation-industry-email-list"|href="https://unlimited-leads.online/pt/transportation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-industry-email-list"|href="https://unlimited-leads.online/pt/travel-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/utilities-industry-email-list"|href="https://unlimited-leads.online/pt/utilities-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/venture-capital-and-private-equity-industry-email-list"|href="https://unlimited-leads.online/pt/venture-capital-and-private-equity-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehousing-industry-email-list"|href="https://unlimited-leads.online/pt/warehousing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wholesale-industry-email-list"|href="https://unlimited-leads.online/pt/wholesale-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wine-and-spirits-industry-email-list"|href="https://unlimited-leads.online/pt/wine-and-spirits-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/writing-and-editing-industry-email-list"|href="https://unlimited-leads.online/pt/writing-and-editing-industry-email-list"|g' "$TEST_FILE"

        # BUSINESS & RETAIL EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/auto-dealer-email-list"|href="https://unlimited-leads.online/pt/auto-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-mechanic-email-list"|href="https://unlimited-leads.online/pt/automotive-mechanic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bank-email-list"|href="https://unlimited-leads.online/pt/bank-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/barber-email-list"|href="https://unlimited-leads.online/pt/barber-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-owner-email-list"|href="https://unlimited-leads.online/pt/business-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/caterer-email-list"|href="https://unlimited-leads.online/pt/caterer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cleaning-service-email-list"|href="https://unlimited-leads.online/pt/cleaning-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-companies-email-list"|href="https://unlimited-leads.online/pt/construction-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-email-list"|href="https://unlimited-leads.online/pt/construction-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractor-email-list"|href="https://unlimited-leads.online/pt/contractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractors-email-list"|href="https://unlimited-leads.online/pt/contractors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/convenience-store-owner-email-list"|href="https://unlimited-leads.online/pt/convenience-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/courier-service-email-list"|href="https://unlimited-leads.online/pt/courier-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/delivery-service-email-list"|href="https://unlimited-leads.online/pt/delivery-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dry-cleaner-email-list"|href="https://unlimited-leads.online/pt/dry-cleaner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-small-business-owners"|href="https://unlimited-leads.online/pt/email-list-of-small-business-owners"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-beverage-email-list"|href="https://unlimited-leads.online/pt/food-beverage-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-processing-company-email-list"|href="https://unlimited-leads.online/pt/food-processing-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-truck-owner-email-list"|href="https://unlimited-leads.online/pt/food-truck-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pteight-broker-email-list"|href="https://unlimited-leads.online/pt/pteight-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-director-email-list"|href="https://unlimited-leads.online/pt/funeral-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-home-email-list"|href="https://unlimited-leads.online/pt/funeral-home-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gas-station-owner-email-list"|href="https://unlimited-leads.online/pt/gas-station-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gift-shop-email-list"|href="https://unlimited-leads.online/pt/gift-shop-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/grocery-store-manager-email-list"|href="https://unlimited-leads.online/pt/grocery-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hotel-email-list"|href="https://unlimited-leads.online/pt/hotel-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agent-email-list"|href="https://unlimited-leads.online/pt/insurance-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agents-email-list"|href="https://unlimited-leads.online/pt/insurance-agents-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/janitorial-service-email-list"|href="https://unlimited-leads.online/pt/janitorial-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/jewelry-store-email-list"|href="https://unlimited-leads.online/pt/jewelry-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/laundromat-owner-email-list"|href="https://unlimited-leads.online/pt/laundromat-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/loan-officer-email-list"|href="https://unlimited-leads.online/pt/loan-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/locksmith-email-list"|href="https://unlimited-leads.online/pt/locksmith-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-coordinator-email-list"|href="https://unlimited-leads.online/pt/logistics-coordinator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-manager-email-list"|href="https://unlimited-leads.online/pt/manufacturing-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-agency-email-list"|href="https://unlimited-leads.online/pt/marketing-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-broker-email-list"|href="https://unlimited-leads.online/pt/mortgage-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-brokers-email-list"|href="https://unlimited-leads.online/pt/mortgage-brokers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/moving-company-email-list"|href="https://unlimited-leads.online/pt/moving-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/organic-food-producer-email-list"|href="https://unlimited-leads.online/pt/organic-food-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-company-email-list"|href="https://unlimited-leads.online/pt/pest-control-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-email-list"|href="https://unlimited-leads.online/pt/pest-control-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pet-store-owner-email-list"|href="https://unlimited-leads.online/pt/pet-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-management-companies-email-list"|href="https://unlimited-leads.online/pt/property-management-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-manager-email-list"|href="https://unlimited-leads.online/pt/property-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recycling-company-email-list"|href="https://unlimited-leads.online/pt/recycling-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/renewable-energy-company-email-list"|href="https://unlimited-leads.online/pt/renewable-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-email-list"|href="https://unlimited-leads.online/pt/restaurant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-industry-email-list"|href="https://unlimited-leads.online/pt/restaurant-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-email-list"|href="https://unlimited-leads.online/pt/retail-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-manager-email-list"|href="https://unlimited-leads.online/pt/retail-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/security-company-email-list"|href="https://unlimited-leads.online/pt/security-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/shipping-company-email-list"|href="https://unlimited-leads.online/pt/shipping-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/small-business-owners-email-list"|href="https://unlimited-leads.online/pt/small-business-owners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-energy-company-email-list"|href="https://unlimited-leads.online/pt/solar-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/supply-chain-email-list"|href="https://unlimited-leads.online/pt/supply-chain-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agency-email-list"|href="https://unlimited-leads.online/pt/travel-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agent-email-list"|href="https://unlimited-leads.online/pt/travel-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-and-tourism-email-list"|href="https://unlimited-leads.online/pt/travel-and-tourism-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/trucking-company-email-list"|href="https://unlimited-leads.online/pt/trucking-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehouse-manager-email-list"|href="https://unlimited-leads.online/pt/warehouse-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/waste-management-company-email-list"|href="https://unlimited-leads.online/pt/waste-management-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wind-energy-company-email-list"|href="https://unlimited-leads.online/pt/wind-energy-company-email-list"|g' "$TEST_FILE"

        # SKILLED TRADES & SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/appliance-repair-technician-email-list"|href="https://unlimited-leads.online/pt/appliance-repair-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/carpet-installer-email-list"|href="https://unlimited-leads.online/pt/carpet-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologist-email-list"|href="https://unlimited-leads.online/pt/cosmetologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologists-email-list"|href="https://unlimited-leads.online/pt/cosmetologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrician-email-list"|href="https://unlimited-leads.online/pt/electrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/esthetician-email-list"|href="https://unlimited-leads.online/pt/esthetician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/flooring-installer-email-list"|href="https://unlimited-leads.online/pt/flooring-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hair-stylist-email-list"|href="https://unlimited-leads.online/pt/hair-stylist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hvac-technician-email-list"|href="https://unlimited-leads.online/pt/hvac-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/landscaper-email-list"|href="https://unlimited-leads.online/pt/landscaper-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nail-technician-email-list"|href="https://unlimited-leads.online/pt/nail-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/painter-email-list"|href="https://unlimited-leads.online/pt/painter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plumbers-email-list"|href="https://unlimited-leads.online/pt/plumbers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/private-security-guard-email-list"|href="https://unlimited-leads.online/pt/private-security-guard-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/roofer-email-list"|href="https://unlimited-leads.online/pt/roofer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-panel-installer-email-list"|href="https://unlimited-leads.online/pt/solar-panel-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tree-service-email-list"|href="https://unlimited-leads.online/pt/tree-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/welder-email-list"|href="https://unlimited-leads.online/pt/welder-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/window-installer-email-list"|href="https://unlimited-leads.online/pt/window-installer-email-list"|g' "$TEST_FILE"

        # CREATIVE & MEDIA EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/art-director-email-list"|href="https://unlimited-leads.online/pt/art-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/content-creator-email-list"|href="https://unlimited-leads.online/pt/content-creator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-interior-designers"|href="https://unlimited-leads.online/pt/email-list-of-interior-designers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-organizers-email-list"|href="https://unlimited-leads.online/pt/event-organizers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-planner-email-list"|href="https://unlimited-leads.online/pt/event-planner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/film-producer-email-list"|href="https://unlimited-leads.online/pt/film-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/graphic-designer-email-list"|href="https://unlimited-leads.online/pt/graphic-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interior-designer-email-list"|href="https://unlimited-leads.online/pt/interior-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/photographer-email-list"|href="https://unlimited-leads.online/pt/photographer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-media-manager-email-list"|href="https://unlimited-leads.online/pt/social-media-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/video-producer-email-list"|href="https://unlimited-leads.online/pt/video-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/web-designer-email-list"|href="https://unlimited-leads.online/pt/web-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wedding-planner-email-list"|href="https://unlimited-leads.online/pt/wedding-planner-email-list"|g' "$TEST_FILE"

        # FITNESS & SPORTS EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/fitness-instructor-email-list"|href="https://unlimited-leads.online/pt/fitness-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-course-email-list"|href="https://unlimited-leads.online/pt/golf-course-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-pro-email-list"|href="https://unlimited-leads.online/pt/golf-pro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gym-owner-email-list"|href="https://unlimited-leads.online/pt/gym-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pilates-instructor-email-list"|href="https://unlimited-leads.online/pt/pilates-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recreation-center-email-list"|href="https://unlimited-leads.online/pt/recreation-center-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spa-owner-email-list"|href="https://unlimited-leads.online/pt/spa-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-coach-email-list"|href="https://unlimited-leads.online/pt/sports-coach-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-equipment-dealer-email-list"|href="https://unlimited-leads.online/pt/sports-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/swimming-instructor-email-list"|href="https://unlimited-leads.online/pt/swimming-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tennis-instructor-email-list"|href="https://unlimited-leads.online/pt/tennis-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/yoga-instructor-email-list"|href="https://unlimited-leads.online/pt/yoga-instructor-email-list"|g' "$TEST_FILE"

        # AGRICULTURE & FARMING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/crop-farmer-email-list"|href="https://unlimited-leads.online/pt/crop-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dairy-farmer-email-list"|href="https://unlimited-leads.online/pt/dairy-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/farmer-email-list"|href="https://unlimited-leads.online/pt/farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/livestock-farmer-email-list"|href="https://unlimited-leads.online/pt/livestock-farmer-email-list"|g' "$TEST_FILE"

        # GOVERNMENT & PUBLIC SERVICE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/city-council-email-list"|href="https://unlimited-leads.online/pt/city-council-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/community-organizer-email-list"|href="https://unlimited-leads.online/pt/community-organizer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/county-official-email-list"|href="https://unlimited-leads.online/pt/county-official-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/firefighter-email-list"|href="https://unlimited-leads.online/pt/firefighter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-employee-email-list"|href="https://unlimited-leads.online/pt/government-employee-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mayor-email-list"|href="https://unlimited-leads.online/pt/mayor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/municipal-worker-email-list"|href="https://unlimited-leads.online/pt/municipal-worker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/police-department-email-list"|href="https://unlimited-leads.online/pt/police-department-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-worker-email-list"|href="https://unlimited-leads.online/pt/social-worker-email-list"|g' "$TEST_FILE"

        ((PROCESSED++))
    else
        echo "Skipping: $TEST_FILE (not a file)"
        ((SKIPPED++))
    fi
done

echo ""
echo "=== PROCESSING COMPLETE ==="
echo "Processed: $PROCESSED files"
echo "Skipped: $SKIPPED files"
