#!/bin/bash

# BATCH LINK REPLACEMENT FOR ALL /de FOLDER FILES
echo "=== BATCH GERMAN LINK REPLACEMENT ==="
echo "Target: ALL .html files in /de/ folder"

# Check if /de directory exists
if [ ! -d "de" ]; then
    echo "Error: /de directory not found!"
    exit 1
fi

# Count total files to process
TOTAL_FILES=$(find de/ -name "*.html" | wc -l)
echo "Found $TOTAL_FILES HTML files to process"

# Process each file
PROCESSED=0
SKIPPED=0

for TEST_FILE in de/*.html; do
    if [ -f "$TEST_FILE" ]; then
        echo ""
        echo "Processing: $TEST_FILE"
        
        # MAIN PAGES
        sed -i 's|href="https://unlimited-leads.online/about-us"|href="https://unlimited-leads.online/de/about-us"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/account"|href="https://unlimited-leads.online/de/account"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/alternatives"|href="https://unlimited-leads.online/de/alternatives"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api-documentation"|href="https://unlimited-leads.online/de/api-documentation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/api"|href="https://unlimited-leads.online/de/api"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/app"|href="https://unlimited-leads.online/de/app"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/confirmation"|href="https://unlimited-leads.online/de/confirmation"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/demo"|href="https://unlimited-leads.online/de/demo"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-verification"|href="https://unlimited-leads.online/de/email-verification"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/index"|href="https://unlimited-leads.online/de/index"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/login"|href="https://unlimited-leads.online/de/login"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pricing"|href="https://unlimited-leads.online/de/pricing"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sign-up"|href="https://unlimited-leads.online/de/sign-up"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signup"|href="https://unlimited-leads.online/de/signup"|g' "$TEST_FILE"

        # FREE TOOLS
        sed -i 's|href="https://unlimited-leads.online/bulk-email-finder"|href="https://unlimited-leads.online/de/bulk-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spam-words-checker"|href="https://unlimited-leads.online/de/spam-words-checker"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-email-from-phone-number"|href="https://unlimited-leads.online/de/find-email-from-phone-number"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bulk-mx-lookup"|href="https://unlimited-leads.online/de/bulk-mx-lookup"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-extractor"|href="https://unlimited-leads.online/de/email-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spintax-generator"|href="https://unlimited-leads.online/de/spintax-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-permutator"|href="https://unlimited-leads.online/de/email-permutator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/google-map-scraper"|href="https://unlimited-leads.online/de/google-map-scraper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-email-finder"|href="https://unlimited-leads.online/de/apollo-email-finder"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-template-generator"|href="https://unlimited-leads.online/de/ai-email-template-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ai-email-reply-generator-free"|href="https://unlimited-leads.online/de/ai-email-reply-generator-free"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cold-email-generator"|href="https://unlimited-leads.online/de/cold-email-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-name-generator"|href="https://unlimited-leads.online/de/email-name-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-headline-generator"|href="https://unlimited-leads.online/de/linkedin-headline-generator"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-sales-navigator-scrapper"|href="https://unlimited-leads.online/de/linkedin-sales-navigator-scrapper"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/domain-extractor"|href="https://unlimited-leads.online/de/domain-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/phone-number-extractor"|href="https://unlimited-leads.online/de/phone-number-extractor"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/find-website-from-company-name-in-bulk"|href="https://unlimited-leads.online/de/find-website-from-company-name-in-bulk"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-profile-url-finder"|href="https://unlimited-leads.online/de/linkedin-profile-url-finder"|g' "$TEST_FILE"

        # ALTERNATIVE COMPARISON PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-alternative"|href="https://unlimited-leads.online/de/adapt-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-alternative"|href="https://unlimited-leads.online/de/apollo-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-alternative"|href="https://unlimited-leads.online/de/cognism-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contact-out-alternative"|href="https://unlimited-leads.online/de/contact-out-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-alternative"|href="https://unlimited-leads.online/de/evaboot-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-alternative"|href="https://unlimited-leads.online/de/findthatlead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-alternative"|href="https://unlimited-leads.online/de/getprospect-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-alternative"|href="https://unlimited-leads.online/de/hunter-io-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-alternative"|href="https://unlimited-leads.online/de/lead411-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-alternative"|href="https://unlimited-leads.online/de/leadfuze-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-alternative"|href="https://unlimited-leads.online/de/leadiq-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-alternative"|href="https://unlimited-leads.online/de/lusha-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-alternative"|href="https://unlimited-leads.online/de/rocketreach-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-alternative"|href="https://unlimited-leads.online/de/scrupp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-alternative"|href="https://unlimited-leads.online/de/seamless-ai-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-alternative"|href="https://unlimited-leads.online/de/signal-hire-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-alternative"|href="https://unlimited-leads.online/de/skrapp-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-alternative"|href="https://unlimited-leads.online/de/snov-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-alternative"|href="https://unlimited-leads.online/de/uplead-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-alternative"|href="https://unlimited-leads.online/de/wiza-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-alternative"|href="https://unlimited-leads.online/de/woodpecker-alternative"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-alternative"|href="https://unlimited-leads.online/de/zoominfo-alternative"|g' "$TEST_FILE"

        # COMPETITOR PAGES
        sed -i 's|href="https://unlimited-leads.online/adapt-io-competitors"|href="https://unlimited-leads.online/de/adapt-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aeroleads-competitors"|href="https://unlimited-leads.online/de/aeroleads-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-competitors"|href="https://unlimited-leads.online/de/apollo-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apollo-io-competitors"|href="https://unlimited-leads.online/de/apollo-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cognism-competitors"|href="https://unlimited-leads.online/de/cognism-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contactout-competitors"|href="https://unlimited-leads.online/de/contactout-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/evaboot-competitors"|href="https://unlimited-leads.online/de/evaboot-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/findthatlead-competitors"|href="https://unlimited-leads.online/de/findthatlead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/getprospect-competitors"|href="https://unlimited-leads.online/de/getprospect-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hunter-io-competitors"|href="https://unlimited-leads.online/de/hunter-io-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lead411-competitors"|href="https://unlimited-leads.online/de/lead411-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadfuze-competitors"|href="https://unlimited-leads.online/de/leadfuze-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leadiq-competitors"|href="https://unlimited-leads.online/de/leadiq-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/linkedin-competitors"|href="https://unlimited-leads.online/de/linkedin-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/lusha-competitors"|href="https://unlimited-leads.online/de/lusha-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rocketreach-competitors"|href="https://unlimited-leads.online/de/rocketreach-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/scrupp-competitors"|href="https://unlimited-leads.online/de/scrupp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/seamless-ai-competitors"|href="https://unlimited-leads.online/de/seamless-ai-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/signal-hire-competitors"|href="https://unlimited-leads.online/de/signal-hire-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/skrapp-competitors"|href="https://unlimited-leads.online/de/skrapp-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/snov-competitors"|href="https://unlimited-leads.online/de/snov-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/uplead-competitors"|href="https://unlimited-leads.online/de/uplead-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/voilanorbert-competitors"|href="https://unlimited-leads.online/de/voilanorbert-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wiza-competitors"|href="https://unlimited-leads.online/de/wiza-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/woodpecker-competitors"|href="https://unlimited-leads.online/de/woodpecker-competitors"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/zoominfo-competitors"|href="https://unlimited-leads.online/de/zoominfo-competitors"|g' "$TEST_FILE"

        # EXECUTIVE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/cdo-email-list"|href="https://unlimited-leads.online/de/cdo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ceo-email-list"|href="https://unlimited-leads.online/de/ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cfo-email-list"|href="https://unlimited-leads.online/de/cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-data-officer-email-list"|href="https://unlimited-leads.online/de/chief-data-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-information-security-officer-email-list"|href="https://unlimited-leads.online/de/chief-information-security-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-medical-officer-email-list"|href="https://unlimited-leads.online/de/chief-medical-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-revenue-officers-email-list"|href="https://unlimited-leads.online/de/chief-revenue-officers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chief-sales-officer-email-list"|href="https://unlimited-leads.online/de/chief-sales-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chro-email-list"|href="https://unlimited-leads.online/de/chro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cio-email-list"|href="https://unlimited-leads.online/de/cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cmo-email-list"|href="https://unlimited-leads.online/de/cmo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cno-email-list"|href="https://unlimited-leads.online/de/cno-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/coo-email-list"|href="https://unlimited-leads.online/de/coo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cso-email-list"|href="https://unlimited-leads.online/de/cso-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cto-email-list"|href="https://unlimited-leads.online/de/cto-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cxo-email-list"|href="https://unlimited-leads.online/de/cxo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-email-list"|href="https://unlimited-leads.online/de/vp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-business-development-email-list"|href="https://unlimited-leads.online/de/vp-of-business-development-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/vp-of-sales-email-list"|href="https://unlimited-leads.online/de/vp-of-sales-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - MEDICAL SPECIALISTS
        sed -i 's|href="https://unlimited-leads.online/anesthesiologist-email-list"|href="https://unlimited-leads.online/de/anesthesiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiologist-email-list"|href="https://unlimited-leads.online/de/cardiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chiropractor-email-list"|href="https://unlimited-leads.online/de/chiropractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetic-surgeons-email-list"|href="https://unlimited-leads.online/de/cosmetic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dentist-email-list"|href="https://unlimited-leads.online/de/dentist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/denturists-email-list"|href="https://unlimited-leads.online/de/denturists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dermatologist-email-list"|href="https://unlimited-leads.online/de/dermatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endocrinologist-email-list"|href="https://unlimited-leads.online/de/endocrinologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/endodontists-email-list"|href="https://unlimited-leads.online/de/endodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialist-email-list"|href="https://unlimited-leads.online/de/ent-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ent-specialists-email-list"|href="https://unlimited-leads.online/de/ent-specialists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/epidemiologist-email-list"|href="https://unlimited-leads.online/de/epidemiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-medicine-specialist-email-list"|href="https://unlimited-leads.online/de/family-medicine-specialist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-practitioners-directors-email-list"|href="https://unlimited-leads.online/de/family-practitioners-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-therapist-email-list"|href="https://unlimited-leads.online/de/family-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gastroenterologist-email-list"|href="https://unlimited-leads.online/de/gastroenterologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioner-email-list"|href="https://unlimited-leads.online/de/general-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-practitioners-email-list"|href="https://unlimited-leads.online/de/general-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/general-surgery-email-list"|href="https://unlimited-leads.online/de/general-surgery-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/geriatrician-email-list"|href="https://unlimited-leads.online/de/geriatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gynecologist-email-list"|href="https://unlimited-leads.online/de/gynecologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hematologist-email-list"|href="https://unlimited-leads.online/de/hematologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/immunologist-email-list"|href="https://unlimited-leads.online/de/immunologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interventional-cardiologists-email-list"|href="https://unlimited-leads.online/de/interventional-cardiologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-director-email-list"|href="https://unlimited-leads.online/de/medical-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neonatologist-email-list"|href="https://unlimited-leads.online/de/neonatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nephrologist-email-list"|href="https://unlimited-leads.online/de/nephrologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurologist-email-list"|href="https://unlimited-leads.online/de/neurologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/neurosurgeons-email-list"|href="https://unlimited-leads.online/de/neurosurgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oncologist-email-list"|href="https://unlimited-leads.online/de/oncologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ophthalmologist-email-list"|href="https://unlimited-leads.online/de/ophthalmologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-pathologists-email-list"|href="https://unlimited-leads.online/de/oral-pathologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oral-surgeons-email-list"|href="https://unlimited-leads.online/de/oral-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthodontist-email-list"|href="https://unlimited-leads.online/de/orthodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/otolaryngologist-email-list"|href="https://unlimited-leads.online/de/otolaryngologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pathologist-email-list"|href="https://unlimited-leads.online/de/pathologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatric-dentists-email-list"|href="https://unlimited-leads.online/de/pediatric-dentists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pediatrician-email-list"|href="https://unlimited-leads.online/de/pediatrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/periodontist-email-list"|href="https://unlimited-leads.online/de/periodontist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacist-email-list"|href="https://unlimited-leads.online/de/pharmacist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-email-list"|href="https://unlimited-leads.online/de/physician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physician-recruiters-email-list"|href="https://unlimited-leads.online/de/physician-recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plastic-surgeons-email-list"|href="https://unlimited-leads.online/de/plastic-surgeons-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/prosthodontists-email-list"|href="https://unlimited-leads.online/de/prosthodontists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychiatrist-email-list"|href="https://unlimited-leads.online/de/psychiatrist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/psychologist-email-list"|href="https://unlimited-leads.online/de/psychologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pulmonologist-email-list"|href="https://unlimited-leads.online/de/pulmonologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/radiologist-email-list"|href="https://unlimited-leads.online/de/radiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rheumatologist-email-list"|href="https://unlimited-leads.online/de/rheumatologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/rhinologists-email-list"|href="https://unlimited-leads.online/de/rhinologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/surgeon-email-list"|href="https://unlimited-leads.online/de/surgeon-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/urologist-email-list"|href="https://unlimited-leads.online/de/urologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/veterinarian-email-list"|href="https://unlimited-leads.online/de/veterinarian-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - NURSES & HEALTHCARE STAFF
        sed -i 's|href="https://unlimited-leads.online/acute-care-nurse-practitioners-email-list"|href="https://unlimited-leads.online/de/acute-care-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/ambulatory-care-nurses-email-list"|href="https://unlimited-leads.online/de/ambulatory-care-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cardiovascular-technologist-email-list"|href="https://unlimited-leads.online/de/cardiovascular-technologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/certified-registered-nurse-anaesthetist-email-list"|href="https://unlimited-leads.online/de/certified-registered-nurse-anaesthetist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/family-nurse-practitioners-email-list"|href="https://unlimited-leads.online/de/family-nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/licensed-practical-nurse-email-list"|href="https://unlimited-leads.online/de/licensed-practical-nurse-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/midwife-nurses-email-list"|href="https://unlimited-leads.online/de/midwife-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioner-email-list"|href="https://unlimited-leads.online/de/nurse-practitioner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurse-practitioners-email-list"|href="https://unlimited-leads.online/de/nurse-practitioners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nurses-email-list"|href="https://unlimited-leads.online/de/nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-health-nurses-email-list"|href="https://unlimited-leads.online/de/occupational-health-nurses-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/orthopedic-nurses-email-list"|href="https://unlimited-leads.online/de/orthopedic-nurses-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - FACILITIES & ORGANIZATIONS
        sed -i 's|href="https://unlimited-leads.online/ambulatory-surgery-centers-email-list"|href="https://unlimited-leads.online/de/ambulatory-surgery-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/blood-bank-centers-email-list"|href="https://unlimited-leads.online/de/blood-bank-centers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/clinics-email-list"|href="https://unlimited-leads.online/de/clinics-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-equipment-manufacturers-email-list"|href="https://unlimited-leads.online/de/dental-equipment-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-email-list"|href="https://unlimited-leads.online/de/healthcare-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-executives-email-list"|href="https://unlimited-leads.online/de/healthcare-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/healthcare-industry-email-list"|href="https://unlimited-leads.online/de/healthcare-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hipaa-compliance-managers-email-list"|href="https://unlimited-leads.online/de/hipaa-compliance-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-ceo-email-list"|href="https://unlimited-leads.online/de/hospital-ceo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cfo-email-list"|href="https://unlimited-leads.online/de/hospital-cfo-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-cio-email-list"|href="https://unlimited-leads.online/de/hospital-cio-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-decision-makers-email-list"|href="https://unlimited-leads.online/de/hospital-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-email-list"|href="https://unlimited-leads.online/de/hospital-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospital-procurement-email-list"|href="https://unlimited-leads.online/de/hospital-procurement-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitals-email-list"|href="https://unlimited-leads.online/de/hospitals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/med-spa-email-list"|href="https://unlimited-leads.online/de/med-spa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-industry-email-list"|href="https://unlimited-leads.online/de/medical-device-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-device-manufacturers-email-list"|href="https://unlimited-leads.online/de/medical-device-manufacturers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/medical-email-list"|href="https://unlimited-leads.online/de/medical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nursing-homes-email-list"|href="https://unlimited-leads.online/de/nursing-homes-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmaceutical-email-list"|href="https://unlimited-leads.online/de/pharmaceutical-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pharmacy-email-list"|href="https://unlimited-leads.online/de/pharmacy-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapy-email-list"|href="https://unlimited-leads.online/de/physical-therapy-email-list"|g' "$TEST_FILE"

        # HEALTHCARE EMAIL LISTS - OTHER PROFESSIONALS
        sed -i 's|href="https://unlimited-leads.online/audiologist-email-list"|href="https://unlimited-leads.online/de/audiologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dental-hygenist-email-list"|href="https://unlimited-leads.online/de/dental-hygenist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/emt-email-list"|href="https://unlimited-leads.online/de/emt-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/massage-therapist-email-list"|href="https://unlimited-leads.online/de/massage-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-counselor-email-list"|href="https://unlimited-leads.online/de/mental-health-counselor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mental-health-professionals-email-list"|href="https://unlimited-leads.online/de/mental-health-professionals-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nutritionist-email-list"|href="https://unlimited-leads.online/de/nutritionist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/occupational-therapist-email-list"|href="https://unlimited-leads.online/de/occupational-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paramedic-email-list"|href="https://unlimited-leads.online/de/paramedic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-trainer-email-list"|href="https://unlimited-leads.online/de/personal-trainer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/physical-therapist-email-list"|href="https://unlimited-leads.online/de/physical-therapist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/therapist-email-list"|href="https://unlimited-leads.online/de/therapist-email-list"|g' "$TEST_FILE"

        # PROFESSIONAL SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/accountants-email-list"|href="https://unlimited-leads.online/de/accountants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-clerk-email-list"|href="https://unlimited-leads.online/de/accounting-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/accounting-email-list"|href="https://unlimited-leads.online/de/accounting-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architect-email-list"|href="https://unlimited-leads.online/de/architect-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/attorney-email-list"|href="https://unlimited-leads.online/de/attorney-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/auditors-email-list"|href="https://unlimited-leads.online/de/auditors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bankruptcy-lawyers-email-list"|href="https://unlimited-leads.online/de/bankruptcy-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/copywriter-email-list"|href="https://unlimited-leads.online/de/copywriter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cpa-email-list"|href="https://unlimited-leads.online/de/cpa-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/criminal-lawyers-email-list"|href="https://unlimited-leads.online/de/criminal-lawyers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-consultant-email-list"|href="https://unlimited-leads.online/de/environmental-consultant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/financial-clerk-email-list"|href="https://unlimited-leads.online/de/financial-clerk-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/law-firms-email-list"|href="https://unlimited-leads.online/de/law-firms-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/personal-injury-lawyers-email-list"|href="https://unlimited-leads.online/de/personal-injury-lawyers-email-list"|g' "$TEST_FILE"

        # HR & MANAGEMENT EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/brand-manager-email-list"|href="https://unlimited-leads.online/de/brand-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/executive-assistants-email-list"|href="https://unlimited-leads.online/de/executive-assistants-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-management-email-list"|href="https://unlimited-leads.online/de/facility-management-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facility-managers-email-list"|href="https://unlimited-leads.online/de/facility-managers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-directors-email-list"|href="https://unlimited-leads.online/de/hr-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-email-list"|href="https://unlimited-leads.online/de/hr-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hr-executives-email-list"|href="https://unlimited-leads.online/de/hr-executives-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/human-resources-email-list"|href="https://unlimited-leads.online/de/human-resources-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-directors-email-list"|href="https://unlimited-leads.online/de/marketing-directors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recruiters-email-list"|href="https://unlimited-leads.online/de/recruiters-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sales-director-email-list"|href="https://unlimited-leads.online/de/sales-director-email-list"|g' "$TEST_FILE"

        # EDUCATION EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/athletic-director-email-list"|href="https://unlimited-leads.online/de/athletic-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/librarian-email-list"|href="https://unlimited-leads.online/de/librarian-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/principal-email-list"|href="https://unlimited-leads.online/de/principal-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/superintendent-email-list"|href="https://unlimited-leads.online/de/superintendent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/teacher-email-list"|href="https://unlimited-leads.online/de/teacher-email-list"|g' "$TEST_FILE"

        # TECHNOLOGY & ENGINEERING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/engineer-email-list"|href="https://unlimited-leads.online/de/engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/engineering-email-list"|href="https://unlimited-leads.online/de/engineering-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-engineers"|href="https://unlimited-leads.online/de/email-list-of-engineers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-engineer-email-list"|href="https://unlimited-leads.online/de/environmental-engineer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/it-decision-makers-email-list"|href="https://unlimited-leads.online/de/it-decision-makers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/msp-email-list"|href="https://unlimited-leads.online/de/msp-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/software-engineers-email-list"|href="https://unlimited-leads.online/de/software-engineers-email-list"|g' "$TEST_FILE"

        # INDUSTRY EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/ada-email-list"|href="https://unlimited-leads.online/de/ada-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-agencies-email-list"|href="https://unlimited-leads.online/de/advertising-agencies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/advertising-professional-email-list"|href="https://unlimited-leads.online/de/advertising-professional-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agricultural-equipment-dealer-email-list"|href="https://unlimited-leads.online/de/agricultural-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/agriculture-industry-email-list"|href="https://unlimited-leads.online/de/agriculture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/airlines-industry-email-list"|href="https://unlimited-leads.online/de/airlines-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/animation-industry-email-list"|href="https://unlimited-leads.online/de/animation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/apparel-and-fashion-industry-email-list"|href="https://unlimited-leads.online/de/apparel-and-fashion-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architectural-industry-email-list"|href="https://unlimited-leads.online/de/architectural-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/architecture-and-planning-industry-email-list"|href="https://unlimited-leads.online/de/architecture-and-planning-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/arts-and-crafts-industry-email-list"|href="https://unlimited-leads.online/de/arts-and-crafts-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-email-list"|href="https://unlimited-leads.online/de/automotive-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-email-list"|href="https://unlimited-leads.online/de/aviation-and-aerospace-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-and-aerospace-industry-email-list"|href="https://unlimited-leads.online/de/aviation-and-aerospace-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/aviation-industry-email-list"|href="https://unlimited-leads.online/de/aviation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/banking-email-list"|href="https://unlimited-leads.online/de/banking-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/beauty-industry-email-list"|href="https://unlimited-leads.online/de/beauty-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-email-list"|href="https://unlimited-leads.online/de/biotechnology-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/biotechnology-industry-email-list"|href="https://unlimited-leads.online/de/biotechnology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/broadcast-media-industry-email-list"|href="https://unlimited-leads.online/de/broadcast-media-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/building-materials-industry-email-list"|href="https://unlimited-leads.online/de/building-materials-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-supplies-and-equipment-industry-email-list"|href="https://unlimited-leads.online/de/business-supplies-and-equipment-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/call-center-industry-email-list"|href="https://unlimited-leads.online/de/call-center-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/capital-markets-industry-email-list"|href="https://unlimited-leads.online/de/capital-markets-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/chemicals-industry-email-list"|href="https://unlimited-leads.online/de/chemicals-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civic-and-social-organization-industry-email-list"|href="https://unlimited-leads.online/de/civic-and-social-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/civil-engineering-industry-email-list"|href="https://unlimited-leads.online/de/civil-engineering-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-and-network-security-industry-email-list"|href="https://unlimited-leads.online/de/computer-and-network-security-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-networking-industry-email-list"|href="https://unlimited-leads.online/de/computer-networking-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/computer-software-industry-email-list"|href="https://unlimited-leads.online/de/computer-software-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-industry-email-list"|href="https://unlimited-leads.online/de/construction-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-electronics-industry-email-list"|href="https://unlimited-leads.online/de/consumer-electronics-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-goods-industry-email-list"|href="https://unlimited-leads.online/de/consumer-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/consumer-services-industry-email-list"|href="https://unlimited-leads.online/de/consumer-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/defense-and-space-industry-email-list"|href="https://unlimited-leads.online/de/defense-and-space-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/design-industry-email-list"|href="https://unlimited-leads.online/de/design-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/education-industry-email-list"|href="https://unlimited-leads.online/de/education-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrical-and-electronic-manufacturing-industry-email-list"|href="https://unlimited-leads.online/de/electrical-and-electronic-manufacturing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/environmental-services-industry-email-list"|href="https://unlimited-leads.online/de/environmental-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/events-services-industry-email-list"|href="https://unlimited-leads.online/de/events-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/facilities-and-services-industry-email-list"|href="https://unlimited-leads.online/de/facilities-and-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/finance-industry-email-list"|href="https://unlimited-leads.online/de/finance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-and-beverage-industry-email-list"|href="https://unlimited-leads.online/de/food-and-beverage-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/furniture-industry-email-list"|href="https://unlimited-leads.online/de/furniture-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-administration-industry-email-list"|href="https://unlimited-leads.online/de/government-administration-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/health-wellness-and-fitness-industry-email-list"|href="https://unlimited-leads.online/de/health-wellness-and-fitness-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hospitality-industry-email-list"|href="https://unlimited-leads.online/de/hospitality-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/industry-email-list"|href="https://unlimited-leads.online/de/industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-industry-email-list"|href="https://unlimited-leads.online/de/insurance-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/internet-industry-email-list"|href="https://unlimited-leads.online/de/internet-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/legal-services-industry-email-list"|href="https://unlimited-leads.online/de/legal-services-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/leisure-industry-email-list"|href="https://unlimited-leads.online/de/leisure-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-and-supply-chain-industry-email-list"|href="https://unlimited-leads.online/de/logistics-and-supply-chain-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/luxury-goods-and-jewelry-industry-email-list"|href="https://unlimited-leads.online/de/luxury-goods-and-jewelry-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/machinery-industry-email-list"|href="https://unlimited-leads.online/de/machinery-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/management-consulting-industry-email-list"|href="https://unlimited-leads.online/de/management-consulting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-email-list"|href="https://unlimited-leads.online/de/manufacturing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/maritime-industry-email-list"|href="https://unlimited-leads.online/de/maritime-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-and-advertising-industry-email-list"|href="https://unlimited-leads.online/de/marketing-and-advertising-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/media-production-industry-email-list"|href="https://unlimited-leads.online/de/media-production-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mining-industry-email-list"|href="https://unlimited-leads.online/de/mining-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/oil-and-gas-industry-email-list"|href="https://unlimited-leads.online/de/oil-and-gas-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/packaging-industry-email-list"|href="https://unlimited-leads.online/de/packaging-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/paper-and-forest-products-industry-email-list"|href="https://unlimited-leads.online/de/paper-and-forest-products-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/political-organization-industry-email-list"|href="https://unlimited-leads.online/de/political-organization-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/printing-and-publishing-email-list"|href="https://unlimited-leads.online/de/printing-and-publishing-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/public-safety-industry-email-list"|href="https://unlimited-leads.online/de/public-safety-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/railroad-transportation-email-list"|href="https://unlimited-leads.online/de/railroad-transportation-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-email-list"|href="https://unlimited-leads.online/de/retail-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sporting-goods-industry-email-list"|href="https://unlimited-leads.online/de/sporting-goods-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/staffing-and-recruiting-industry-email-list"|href="https://unlimited-leads.online/de/staffing-and-recruiting-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/technology-industry-email-list"|href="https://unlimited-leads.online/de/technology-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/telecom-industry-email-list"|href="https://unlimited-leads.online/de/telecom-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/transportation-industry-email-list"|href="https://unlimited-leads.online/de/transportation-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-industry-email-list"|href="https://unlimited-leads.online/de/travel-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/utilities-industry-email-list"|href="https://unlimited-leads.online/de/utilities-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/venture-capital-and-private-equity-industry-email-list"|href="https://unlimited-leads.online/de/venture-capital-and-private-equity-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehousing-industry-email-list"|href="https://unlimited-leads.online/de/warehousing-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wholesale-industry-email-list"|href="https://unlimited-leads.online/de/wholesale-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wine-and-spirits-industry-email-list"|href="https://unlimited-leads.online/de/wine-and-spirits-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/writing-and-editing-industry-email-list"|href="https://unlimited-leads.online/de/writing-and-editing-industry-email-list"|g' "$TEST_FILE"

        # BUSINESS & RETAIL EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/auto-dealer-email-list"|href="https://unlimited-leads.online/de/auto-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/automotive-mechanic-email-list"|href="https://unlimited-leads.online/de/automotive-mechanic-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/bank-email-list"|href="https://unlimited-leads.online/de/bank-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/barber-email-list"|href="https://unlimited-leads.online/de/barber-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/business-owner-email-list"|href="https://unlimited-leads.online/de/business-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/caterer-email-list"|href="https://unlimited-leads.online/de/caterer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cleaning-service-email-list"|href="https://unlimited-leads.online/de/cleaning-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-companies-email-list"|href="https://unlimited-leads.online/de/construction-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/construction-email-list"|href="https://unlimited-leads.online/de/construction-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractor-email-list"|href="https://unlimited-leads.online/de/contractor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/contractors-email-list"|href="https://unlimited-leads.online/de/contractors-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/convenience-store-owner-email-list"|href="https://unlimited-leads.online/de/convenience-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/courier-service-email-list"|href="https://unlimited-leads.online/de/courier-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/delivery-service-email-list"|href="https://unlimited-leads.online/de/delivery-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dry-cleaner-email-list"|href="https://unlimited-leads.online/de/dry-cleaner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-small-business-owners"|href="https://unlimited-leads.online/de/email-list-of-small-business-owners"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-beverage-email-list"|href="https://unlimited-leads.online/de/food-beverage-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-processing-company-email-list"|href="https://unlimited-leads.online/de/food-processing-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/food-truck-owner-email-list"|href="https://unlimited-leads.online/de/food-truck-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/deeight-broker-email-list"|href="https://unlimited-leads.online/de/deeight-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-director-email-list"|href="https://unlimited-leads.online/de/funeral-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/funeral-home-email-list"|href="https://unlimited-leads.online/de/funeral-home-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gas-station-owner-email-list"|href="https://unlimited-leads.online/de/gas-station-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gift-shop-email-list"|href="https://unlimited-leads.online/de/gift-shop-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/grocery-store-manager-email-list"|href="https://unlimited-leads.online/de/grocery-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hotel-email-list"|href="https://unlimited-leads.online/de/hotel-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agent-email-list"|href="https://unlimited-leads.online/de/insurance-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/insurance-agents-email-list"|href="https://unlimited-leads.online/de/insurance-agents-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/janitorial-service-email-list"|href="https://unlimited-leads.online/de/janitorial-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/jewelry-store-email-list"|href="https://unlimited-leads.online/de/jewelry-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/laundromat-owner-email-list"|href="https://unlimited-leads.online/de/laundromat-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/loan-officer-email-list"|href="https://unlimited-leads.online/de/loan-officer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/locksmith-email-list"|href="https://unlimited-leads.online/de/locksmith-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/logistics-coordinator-email-list"|href="https://unlimited-leads.online/de/logistics-coordinator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/manufacturing-manager-email-list"|href="https://unlimited-leads.online/de/manufacturing-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/marketing-agency-email-list"|href="https://unlimited-leads.online/de/marketing-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-broker-email-list"|href="https://unlimited-leads.online/de/mortgage-broker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mortgage-brokers-email-list"|href="https://unlimited-leads.online/de/mortgage-brokers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/moving-company-email-list"|href="https://unlimited-leads.online/de/moving-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/organic-food-producer-email-list"|href="https://unlimited-leads.online/de/organic-food-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-company-email-list"|href="https://unlimited-leads.online/de/pest-control-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pest-control-email-list"|href="https://unlimited-leads.online/de/pest-control-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pet-store-owner-email-list"|href="https://unlimited-leads.online/de/pet-store-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-management-companies-email-list"|href="https://unlimited-leads.online/de/property-management-companies-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/property-manager-email-list"|href="https://unlimited-leads.online/de/property-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recycling-company-email-list"|href="https://unlimited-leads.online/de/recycling-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/renewable-energy-company-email-list"|href="https://unlimited-leads.online/de/renewable-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-email-list"|href="https://unlimited-leads.online/de/restaurant-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/restaurant-industry-email-list"|href="https://unlimited-leads.online/de/restaurant-industry-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-email-list"|href="https://unlimited-leads.online/de/retail-store-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/retail-store-manager-email-list"|href="https://unlimited-leads.online/de/retail-store-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/security-company-email-list"|href="https://unlimited-leads.online/de/security-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/shipping-company-email-list"|href="https://unlimited-leads.online/de/shipping-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/small-business-owners-email-list"|href="https://unlimited-leads.online/de/small-business-owners-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-energy-company-email-list"|href="https://unlimited-leads.online/de/solar-energy-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/supply-chain-email-list"|href="https://unlimited-leads.online/de/supply-chain-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agency-email-list"|href="https://unlimited-leads.online/de/travel-agency-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-agent-email-list"|href="https://unlimited-leads.online/de/travel-agent-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/travel-and-tourism-email-list"|href="https://unlimited-leads.online/de/travel-and-tourism-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/trucking-company-email-list"|href="https://unlimited-leads.online/de/trucking-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/warehouse-manager-email-list"|href="https://unlimited-leads.online/de/warehouse-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/waste-management-company-email-list"|href="https://unlimited-leads.online/de/waste-management-company-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wind-energy-company-email-list"|href="https://unlimited-leads.online/de/wind-energy-company-email-list"|g' "$TEST_FILE"

        # SKILLED TRADES & SERVICES EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/appliance-repair-technician-email-list"|href="https://unlimited-leads.online/de/appliance-repair-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/carpet-installer-email-list"|href="https://unlimited-leads.online/de/carpet-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologist-email-list"|href="https://unlimited-leads.online/de/cosmetologist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/cosmetologists-email-list"|href="https://unlimited-leads.online/de/cosmetologists-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/electrician-email-list"|href="https://unlimited-leads.online/de/electrician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/esthetician-email-list"|href="https://unlimited-leads.online/de/esthetician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/flooring-installer-email-list"|href="https://unlimited-leads.online/de/flooring-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hair-stylist-email-list"|href="https://unlimited-leads.online/de/hair-stylist-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/hvac-technician-email-list"|href="https://unlimited-leads.online/de/hvac-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/landscaper-email-list"|href="https://unlimited-leads.online/de/landscaper-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/nail-technician-email-list"|href="https://unlimited-leads.online/de/nail-technician-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/painter-email-list"|href="https://unlimited-leads.online/de/painter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/plumbers-email-list"|href="https://unlimited-leads.online/de/plumbers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/private-security-guard-email-list"|href="https://unlimited-leads.online/de/private-security-guard-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/roofer-email-list"|href="https://unlimited-leads.online/de/roofer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/solar-panel-installer-email-list"|href="https://unlimited-leads.online/de/solar-panel-installer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tree-service-email-list"|href="https://unlimited-leads.online/de/tree-service-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/welder-email-list"|href="https://unlimited-leads.online/de/welder-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/window-installer-email-list"|href="https://unlimited-leads.online/de/window-installer-email-list"|g' "$TEST_FILE"

        # CREATIVE & MEDIA EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/art-director-email-list"|href="https://unlimited-leads.online/de/art-director-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/content-creator-email-list"|href="https://unlimited-leads.online/de/content-creator-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/email-list-of-interior-designers"|href="https://unlimited-leads.online/de/email-list-of-interior-designers"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-organizers-email-list"|href="https://unlimited-leads.online/de/event-organizers-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/event-planner-email-list"|href="https://unlimited-leads.online/de/event-planner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/film-producer-email-list"|href="https://unlimited-leads.online/de/film-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/graphic-designer-email-list"|href="https://unlimited-leads.online/de/graphic-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/interior-designer-email-list"|href="https://unlimited-leads.online/de/interior-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/photographer-email-list"|href="https://unlimited-leads.online/de/photographer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-media-manager-email-list"|href="https://unlimited-leads.online/de/social-media-manager-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/video-producer-email-list"|href="https://unlimited-leads.online/de/video-producer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/web-designer-email-list"|href="https://unlimited-leads.online/de/web-designer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/wedding-planner-email-list"|href="https://unlimited-leads.online/de/wedding-planner-email-list"|g' "$TEST_FILE"

        # FITNESS & SPORTS EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/fitness-instructor-email-list"|href="https://unlimited-leads.online/de/fitness-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-course-email-list"|href="https://unlimited-leads.online/de/golf-course-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/golf-pro-email-list"|href="https://unlimited-leads.online/de/golf-pro-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/gym-owner-email-list"|href="https://unlimited-leads.online/de/gym-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/pilates-instructor-email-list"|href="https://unlimited-leads.online/de/pilates-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/recreation-center-email-list"|href="https://unlimited-leads.online/de/recreation-center-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/spa-owner-email-list"|href="https://unlimited-leads.online/de/spa-owner-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-coach-email-list"|href="https://unlimited-leads.online/de/sports-coach-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/sports-equipment-dealer-email-list"|href="https://unlimited-leads.online/de/sports-equipment-dealer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/swimming-instructor-email-list"|href="https://unlimited-leads.online/de/swimming-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/tennis-instructor-email-list"|href="https://unlimited-leads.online/de/tennis-instructor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/yoga-instructor-email-list"|href="https://unlimited-leads.online/de/yoga-instructor-email-list"|g' "$TEST_FILE"

        # AGRICULTURE & FARMING EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/crop-farmer-email-list"|href="https://unlimited-leads.online/de/crop-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/dairy-farmer-email-list"|href="https://unlimited-leads.online/de/dairy-farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/farmer-email-list"|href="https://unlimited-leads.online/de/farmer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/livestock-farmer-email-list"|href="https://unlimited-leads.online/de/livestock-farmer-email-list"|g' "$TEST_FILE"

        # GOVERNMENT & PUBLIC SERVICE EMAIL LISTS
        sed -i 's|href="https://unlimited-leads.online/city-council-email-list"|href="https://unlimited-leads.online/de/city-council-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/community-organizer-email-list"|href="https://unlimited-leads.online/de/community-organizer-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/county-official-email-list"|href="https://unlimited-leads.online/de/county-official-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/firefighter-email-list"|href="https://unlimited-leads.online/de/firefighter-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/government-employee-email-list"|href="https://unlimited-leads.online/de/government-employee-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/mayor-email-list"|href="https://unlimited-leads.online/de/mayor-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/municipal-worker-email-list"|href="https://unlimited-leads.online/de/municipal-worker-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/police-department-email-list"|href="https://unlimited-leads.online/de/police-department-email-list"|g' "$TEST_FILE"
        sed -i 's|href="https://unlimited-leads.online/social-worker-email-list"|href="https://unlimited-leads.online/de/social-worker-email-list"|g' "$TEST_FILE"

        ((PROCESSED++))
    else
        echo "Skipping: $TEST_FILE (not a file)"
        ((SKIPPED++))
    fi
done

echo ""
echo "=== PROCESSING COMPLETE ==="
echo "Processed: $PROCESSED files"
echo "Skipped: $SKIPPED files"
