name: Continuous Translation

on:
  push:
    branches: [ main ]
    paths:
      - '**.html'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: yunwei37/OpenAI-Continuous-Translator@master
        with:
          git_repo_url: https://github.com/eliassaoe/something
          api_key: ${{ secrets.OPENAI_API_KEY }}
          target_language: "Spanish"
          file_types: "html"
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Add Spanish translations'
          default_author: github_actions
